package io.opentelemetry.kotlin.semconv.incubating

/**
 * Autogenerated OpenTelemetry semantic conventions for 'db'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object DbIncubatingAttributes {

    /**
    * <p>The name of the connection pool; unique within the instrumented application. In case the connection pool implementation doesn't provide a name, instrumentation SHOULD use a combination of parameters that would make the name unique, for example, combining attributes <c>server.address</c>, <c>server.port</c>, and <c>db.namespace</c>, formatted as <c>server.address:server.port/db.namespace</c>. Instrumentations that generate connection pool name following different patterns SHOULD document it.</p>
    */
    @IncubatingApi
    const val DB_CLIENT_CONNECTION_POOL_NAME: String = "db.client.connection.pool.name"

    /**
    * <p>The state of a connection in the pool</p>
    */
    @IncubatingApi
    const val DB_CLIENT_CONNECTION_STATE: String = "db.client.connection.state"

    /**
    * <p>A database operation parameter, with <c><key></c> being the parameter name, and the attribute value being a string representation of the parameter value.</p>
    * <p>Notes:</p>
    * <p>For example, a client-side maximum number of rows to read from the database
    * MAY be recorded as the <c>db.operation.parameter.max_rows</c> attribute.</p>
    * <p><c>db.query.text</c> parameters SHOULD be captured using <c>db.query.parameter.<key></c>
    * instead of <c>db.operation.parameter.<key></c>.</p>
    */
    @IncubatingApi
    const val DB_OPERATION_PARAMETER: String = "db.operation.parameter"

    /**
    * <p>A database query parameter, with <c><key></c> being the parameter name, and the attribute value being a string representation of the parameter value.</p>
    * <p>Notes:</p>
    * <p>If a query parameter has no name and instead is referenced only by index,
    * then <c><key></c> SHOULD be the 0-based index.</p>
    * <p><c>db.query.parameter.<key></c> SHOULD match
    * up with the parameterized placeholders present in <c>db.query.text</c>.</p>
    * <p>It is RECOMMENDED to capture the value as provided by the application
    * without attempting to do any case normalization.</p>
    * <p><c>db.query.parameter.<key></c> SHOULD NOT be captured on batch operations.</p>
    * <p>Examples:</p>
    * <ul>
    *   <li>For a query <c>SELECT * FROM users where username =  %s</c> with the parameter <c>"jdoe"</c>,
    * the attribute <c>db.query.parameter.0</c> SHOULD be set to <c>"jdoe"</c>.</li>
    *   <li>For a query <c>"SELECT * FROM users WHERE username = %(userName)s;</c> with parameter
    * <c>userName = "jdoe"</c>, the attribute <c>db.query.parameter.userName</c> SHOULD be set to <c>"jdoe"</c>.</li>
    * </ul>
    */
    @IncubatingApi
    const val DB_QUERY_PARAMETER: String = "db.query.parameter"

    /**
    * <p>Number of rows returned by the operation.</p>
    */
    @IncubatingApi
    const val DB_RESPONSE_RETURNED_ROWS: String = "db.response.returned_rows"

    /**
    * <p>DB_CLIENT_CONNECTION_STATE</p>
    */
    @IncubatingApi
    enum class DbClientConnectionStateValues(val value: String) {

        /**
        * <p>idle.</p>
        */
        IDLE("idle"),

        /**
        * <p>used.</p>
        */
        USED("used"),
    }

}
