package io.opentelemetry.kotlin.semconv.incubating

/**
 * Autogenerated OpenTelemetry semantic conventions for 'deployment'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object DeploymentIncubatingAttributes {

    /**
    * <p>The id of the deployment.</p>
    */
    @IncubatingApi
    const val DEPLOYMENT_ID: String = "deployment.id"

    /**
    * <p>The name of the deployment.</p>
    */
    @IncubatingApi
    const val DEPLOYMENT_NAME: String = "deployment.name"

    /**
    * <p>The status of the deployment.</p>
    */
    @IncubatingApi
    const val DEPLOYMENT_STATUS: String = "deployment.status"

    /**
    * <p>DEPLOYMENT_STATUS</p>
    */
    @IncubatingApi
    enum class DeploymentStatusValues(val value: String) {

        /**
        * <p>failed</p>
        */
        FAILED("failed"),

        /**
        * <p>succeeded</p>
        */
        SUCCEEDED("succeeded"),
    }
}
