package io.opentelemetry.kotlin.semconv.incubating

/**
 * Autogenerated OpenTelemetry semantic conventions for 'http'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object HttpIncubatingAttributes {

    /**
    * <p>State of the HTTP connection in the HTTP connection pool.</p>
    */
    @IncubatingApi
    const val HTTP_CONNECTION_STATE: String = "http.connection.state"

    /**
    * <p>The size of the request payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the <a href="https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length">Content-Length</a> header. For requests using transport encoding, this should be the compressed size.</p>
    */
    @IncubatingApi
    const val HTTP_REQUEST_BODY_SIZE: String = "http.request.body.size"

    /**
    * <p>The total size of the request in bytes. This should be the total number of bytes sent over the wire, including the request line (HTTP/1.1), framing (HTTP/2 and HTTP/3), headers, and request body if any.</p>
    */
    @IncubatingApi
    const val HTTP_REQUEST_SIZE: String = "http.request.size"

    /**
    * <p>The size of the response payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the <a href="https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length">Content-Length</a> header. For requests using transport encoding, this should be the compressed size.</p>
    */
    @IncubatingApi
    const val HTTP_RESPONSE_BODY_SIZE: String = "http.response.body.size"

    /**
    * <p>The total size of the response in bytes. This should be the total number of bytes sent over the wire, including the status line (HTTP/1.1), framing (HTTP/2 and HTTP/3), headers, and response body and trailers if any.</p>
    */
    @IncubatingApi
    const val HTTP_RESPONSE_SIZE: String = "http.response.size"

    /**
    * <p>HTTP_CONNECTION_STATE</p>
    */
    @IncubatingApi
    enum class HttpConnectionStateValues(val value: String) {

        /**
        * <p>active state.</p>
        */
        ACTIVE("active"),

        /**
        * <p>idle state.</p>
        */
        IDLE("idle"),
    }

}
