package io.opentelemetry.kotlin.semconv.incubating

/**
 * Autogenerated OpenTelemetry semantic conventions for 'ios'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object IosIncubatingAttributes {

    /**
    * <p>This attribute represents the state of the application.</p>
    * <p>Notes:</p>
    * <p>The iOS lifecycle states are defined in the <a href="https://developer.apple.com/documentation/uikit/uiapplicationdelegate">UIApplicationDelegate documentation</a>, and from which the <c>OS terminology</c> column values are derived.</p>
    */
    @IncubatingApi
    const val IOS_APP_STATE: String = "ios.app.state"

    /**
    * <p>IOS_APP_STATE</p>
    */
    @IncubatingApi
    enum class IosAppStateValues(val value: String) {

        /**
        * <p>The app has become <c>active</c>. Associated with UIKit notification <c>applicationDidBecomeActive</c>.</p>
        */
        ACTIVE("active"),

        /**
        * <p>The app is now <c>inactive</c>. Associated with UIKit notification <c>applicationWillResignActive</c>.</p>
        */
        INACTIVE("inactive"),

        /**
        * <p>The app is now in the background. This value is associated with UIKit notification <c>applicationDidEnterBackground</c>.</p>
        */
        BACKGROUND("background"),

        /**
        * <p>The app is now in the foreground. This value is associated with UIKit notification <c>applicationWillEnterForeground</c>.</p>
        */
        FOREGROUND("foreground"),

        /**
        * <p>The app is about to terminate. Associated with UIKit notification <c>applicationWillTerminate</c>.</p>
        */
        TERMINATE("terminate"),
    }

}
