package io.opentelemetry.kotlin.semconv.incubating

/**
 * Autogenerated OpenTelemetry semantic conventions for 'jvm'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object JvmIncubatingAttributes {

    /**
    * <p>Name of the buffer pool.</p>
    * <p>Notes:</p>
    * <p>Pool names are generally obtained via <a href="https://docs.oracle.com/en/java/javase/11/docs/api/java.management/java/lang/management/BufferPoolMXBean.html#getName()">BufferPoolMXBean#getName()</a>.</p>
    */
    @IncubatingApi
    const val JVM_BUFFER_POOL_NAME: String = "jvm.buffer.pool.name"

    /**
    * <p>Name of the garbage collector cause.</p>
    * <p>Notes:</p>
    * <p>Garbage collector cause is generally obtained via <a href="https://docs.oracle.com/en/java/javase/11/docs/api/jdk.management/com/sun/management/GarbageCollectionNotificationInfo.html#getGcCause()">GarbageCollectionNotificationInfo#getGcCause()</a>.</p>
    */
    @IncubatingApi
    const val JVM_GC_CAUSE: String = "jvm.gc.cause"

}
