package io.opentelemetry.kotlin.semconv.incubating

/**
 * Autogenerated OpenTelemetry semantic conventions for 'rpc'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object RpcIncubatingAttributes {

    /**
    * <p>The fully-qualified logical name of the method from the RPC interface perspective.</p>
    * <p>Notes:</p>
    * <p>The method name MAY have unbounded cardinality in edge or error cases.</p>
    * <p>Some RPC frameworks or libraries provide a fixed set of recognized methods
    * for client stubs and server implementations. Instrumentations for such
    * frameworks MUST set this attribute to the original method name only
    * when the method is recognized by the framework or library.</p>
    * <p>When the method is not recognized, for example, when the server receives
    * a request for a method that is not predefined on the server, or when
    * instrumentation is not able to reliably detect if the method is predefined,
    * the attribute MUST be set to <c>_OTHER</c>. In such cases, tracing
    * instrumentations MUST also set <c>rpc.method_original</c> attribute to
    * the original method value.</p>
    * <p>If the RPC instrumentation could end up converting valid RPC methods to
    * <c>_OTHER</c>, then it SHOULD provide a way to configure the list of recognized
    * RPC methods.</p>
    * <p>The <c>rpc.method</c> can be different from the name of any implementing
    * method/function.
    * The <c>code.function.name</c> attribute may be used to record the fully-qualified
    * method actually executing the call on the server side, or the
    * RPC client stub method on the client side.</p>
    */
    @IncubatingApi
    const val RPC_METHOD: String = "rpc.method"

    /**
    * <p>The original name of the method used by the client.</p>
    */
    @IncubatingApi
    const val RPC_METHOD_ORIGINAL: String = "rpc.method_original"

    /**
    * <p>RPC request metadata, <c><key></c> being the normalized RPC metadata key (lowercase), the value being the metadata values.</p>
    * <p>Notes:</p>
    * <p>Instrumentations SHOULD require an explicit configuration of which metadata values are to be captured.
    * Including all request metadata values can be a security risk - explicit configuration helps avoid leaking sensitive information.</p>
    * <p>For example, a property <c>my-custom-key</c> with value <c>["1.2.3.4", "1.2.3.5"]</c> SHOULD be recorded as
    * <c>rpc.request.metadata.my-custom-key</c> attribute with value <c>["1.2.3.4", "1.2.3.5"]</c></p>
    */
    @IncubatingApi
    const val RPC_REQUEST_METADATA: String = "rpc.request.metadata"

    /**
    * <p>RPC response metadata, <c><key></c> being the normalized RPC metadata key (lowercase), the value being the metadata values.</p>
    * <p>Notes:</p>
    * <p>Instrumentations SHOULD require an explicit configuration of which metadata values are to be captured.
    * Including all response metadata values can be a security risk - explicit configuration helps avoid leaking sensitive information.</p>
    * <p>For example, a property <c>my-custom-key</c> with value <c>["attribute_value"]</c> SHOULD be recorded as
    * the <c>rpc.response.metadata.my-custom-key</c> attribute with value <c>["attribute_value"]</c></p>
    */
    @IncubatingApi
    const val RPC_RESPONSE_METADATA: String = "rpc.response.metadata"

    /**
    * <p>Status code of the RPC returned by the RPC server or generated by the client</p>
    * <p>Notes:</p>
    * <p>Usually it represents an error code, but may also represent partial success, warning, or differentiate between various types of successful outcomes.
    * Semantic conventions for individual RPC frameworks SHOULD document what <c>rpc.response.status_code</c> means in the context of that system and which values are considered to represent errors.</p>
    */
    @IncubatingApi
    const val RPC_RESPONSE_STATUS_CODE: String = "rpc.response.status_code"

    /**
    * <p>The Remote Procedure Call (RPC) system.</p>
    * <p>Notes:</p>
    * <p>The client and server RPC systems may differ for the same RPC interaction. For example, a client may use Apache Dubbo or Connect RPC to communicate with a server that uses gRPC since both protocols provide compatibility with gRPC.</p>
    */
    @IncubatingApi
    const val RPC_SYSTEM_NAME: String = "rpc.system.name"

    /**
    * <p>RPC_SYSTEM_NAME</p>
    */
    @IncubatingApi
    enum class RpcSystemNameValues(val value: String) {

        /**
        * <p><a href="https://grpc.io/">gRPC</a></p>
        */
        GRPC("grpc"),

        /**
        * <p><a href="https://dubbo.apache.org/">Apache Dubbo</a></p>
        */
        DUBBO("dubbo"),

        /**
        * <p><a href="https://connectrpc.com/">Connect RPC</a></p>
        */
        CONNECTRPC("connectrpc"),

        /**
        * <p><a href="https://www.jsonrpc.org/">JSON-RPC</a></p>
        */
        JSONRPC("jsonrpc"),
    }
}
