package io.opentelemetry.kotlin.semconv.incubating

/**
 * Autogenerated OpenTelemetry semantic conventions for 'url'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object UrlIncubatingAttributes {

    /**
    * <p>Domain extracted from the <c>url.full</c>, such as "opentelemetry.io".</p>
    * <p>Notes:</p>
    * <p>In some cases a URL may refer to an IP and/or port directly, without a domain name. In this case, the IP address would go to the domain field. If the URL contains a <a href="https://www.rfc-editor.org/rfc/rfc2732#section-2">literal IPv6 address</a> enclosed by <c>[</c> and <c>]</c>, the <c>[</c> and <c>]</c> characters should also be captured in the domain field.</p>
    */
    @IncubatingApi
    const val URL_DOMAIN: String = "url.domain"

    /**
    * <p>The file extension extracted from the <c>url.full</c>, excluding the leading dot.</p>
    * <p>Notes:</p>
    * <p>The file extension is only set if it exists, as not every url has a file extension. When the file name has multiple extensions <c>example.tar.gz</c>, only the last one should be captured <c>gz</c>, not <c>tar.gz</c>.</p>
    */
    @IncubatingApi
    const val URL_EXTENSION: String = "url.extension"

    /**
    * <p>Unmodified original URL as seen in the event source.</p>
    * <p>Notes:</p>
    * <p>In network monitoring, the observed URL may be a full URL, whereas in access logs, the URL is often just represented as a path. This field is meant to represent the URL as it was observed, complete or not.
    * <c>url.original</c> might contain credentials passed via URL in form of <c>https://username:password@www.example.com/</c>. In such case password and username SHOULD NOT be redacted and attribute's value SHOULD remain the same.</p>
    */
    @IncubatingApi
    const val URL_ORIGINAL: String = "url.original"

    /**
    * <p>Port extracted from the <c>url.full</c></p>
    */
    @IncubatingApi
    const val URL_PORT: String = "url.port"

    /**
    * <p>The highest registered url domain, stripped of the subdomain.</p>
    * <p>Notes:</p>
    * <p>This value can be determined precisely with the <a href="https://publicsuffix.org/">public suffix list</a>. For example, the registered domain for <c>foo.example.com</c> is <c>example.com</c>. Trying to approximate this by simply taking the last two labels will not work well for TLDs such as <c>co.uk</c>.</p>
    */
    @IncubatingApi
    const val URL_REGISTERED_DOMAIN: String = "url.registered_domain"

    /**
    * <p>The subdomain portion of a fully qualified domain name includes all of the names except the host name under the registered_domain. In a partially qualified domain, or if the qualification level of the full name cannot be determined, subdomain contains all of the names below the registered domain.</p>
    * <p>Notes:</p>
    * <p>The subdomain portion of <c>www.east.mydomain.co.uk</c> is <c>east</c>. If the domain has multiple levels of subdomain, such as <c>sub2.sub1.example.com</c>, the subdomain field should contain <c>sub2.sub1</c>, with no trailing period.</p>
    */
    @IncubatingApi
    const val URL_SUBDOMAIN: String = "url.subdomain"

    /**
    * <p>The low-cardinality template of an <a href="https://www.rfc-editor.org/rfc/rfc3986#section-4.2">absolute path reference</a>.</p>
    */
    @IncubatingApi
    const val URL_TEMPLATE: String = "url.template"

    /**
    * <p>The effective top level domain (eTLD), also known as the domain suffix, is the last part of the domain name. For example, the top level domain for example.com is <c>com</c>.</p>
    * <p>Notes:</p>
    * <p>This value can be determined precisely with the <a href="https://publicsuffix.org/">public suffix list</a>.</p>
    */
    @IncubatingApi
    const val URL_TOP_LEVEL_DOMAIN: String = "url.top_level_domain"
}
