#!/bin/bash
set -euo pipefail

# Verifies that the changelog entry for a release version has been merged

if [[ -z "${VERSION:-}" ]]; then
  echo "Error: VERSION environment variable is required" >&2
  exit 1
fi

if [[ -z "${VERSION_PATCH:-}" ]]; then
  echo "Error: VERSION_PATCH environment variable is required" >&2
  exit 1
fi

if [[ $VERSION_PATCH == 0 ]]; then
  # not making a patch release, so changelog entry should exist
  if ! grep --quiet "^## Version $VERSION " CHANGELOG.md; then
    echo "Error: the pull request generated by prepare-release-branch.yml needs to be merged first" >&2
    echo "Expected to find '## Version $VERSION' in CHANGELOG.md" >&2
    exit 1
  fi
  echo "Verified: changelog entry for version $VERSION exists"
else
  echo "Skipped: patch release does not require changelog check"
fi
