package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'client'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object ClientAttributes {
  

    /**
    * <p>Client address - domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.</p>
    * <p>Notes:</p>
    * <p>When observed from the server side, and when communicating through an intermediary, <c>client.address</c> SHOULD represent the client address behind any intermediaries,  for example proxies, if it's available.</p>
    */
    const val CLIENT_ADDRESS: String = "client.address"

    /**
    * <p>Client port number.</p>
    * <p>Notes:</p>
    * <p>When observed from the server side, and when communicating through an intermediary, <c>client.port</c> SHOULD represent the client port behind any intermediaries,  for example proxies, if it's available.</p>
    */
    const val CLIENT_PORT: String = "client.port"
}
