package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'cpu'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object CpuAttributes {
  

    /**
    * <p>The logical CPU number [0..n-1]</p>
    */
    @IncubatingApi
    const val CPU_LOGICAL_NUMBER: String = "cpu.logical_number"

    /**
    * <p>The mode of the CPU</p>
    */
    @IncubatingApi
    const val CPU_MODE: String = "cpu.mode"

    /**
    * <p>CPU_MODE</p>
    */
    @IncubatingApi
    enum class CpuModeValues(val value: String) {

        /**
        * <p>User</p>
        */
        USER("user"),

        /**
        * <p>System</p>
        */
        SYSTEM("system"),

        /**
        * <p>Nice</p>
        */
        NICE("nice"),

        /**
        * <p>Idle</p>
        */
        IDLE("idle"),

        /**
        * <p>IO Wait</p>
        */
        IOWAIT("iowait"),

        /**
        * <p>Interrupt</p>
        */
        INTERRUPT("interrupt"),

        /**
        * <p>Steal</p>
        */
        STEAL("steal"),

        /**
        * <p>Kernel</p>
        */
        KERNEL("kernel"),
    }
}
