package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'event'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EventAttributes {
  

    /**
    * <p>Identifies the class / type of event.</p>
    */
    @Deprecated("Replaced by EventName top-level field on the LogRecord.")
    const val EVENT_NAME: String = "event.name"
}
