package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'oci'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object OciAttributes {
  

    /**
    * <p>The digest of the OCI image manifest. For container images specifically is the digest by which the container image is known.</p>
    * <p>Notes:</p>
    * <p>Follows <a href="https://github.com/opencontainers/image-spec/blob/main/manifest.md">OCI Image Manifest Specification</a>, and specifically the <a href="https://github.com/opencontainers/image-spec/blob/main/descriptor.md#digests">Digest property</a>.
    * An example can be found in <a href="https://github.com/opencontainers/image-spec/blob/main/manifest.md#example-image-manifest">Example Image Manifest</a>.</p>
    */
    @IncubatingApi
    const val OCI_MANIFEST_DIGEST: String = "oci.manifest.digest"
}
