package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'opentracing'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object OpentracingAttributes {
  

    /**
    * <p>Parent-child Reference type</p>
    * <p>Notes:</p>
    * <p>The causal relationship between a child Span and a parent Span.</p>
    */
    @IncubatingApi
    const val OPENTRACING_REF_TYPE: String = "opentracing.ref_type"

    /**
    * <p>OPENTRACING_REF_TYPE</p>
    */
    @IncubatingApi
    enum class OpentracingRefTypeValues(val value: String) {

        /**
        * <p>The parent Span depends on the child Span in some capacity</p>
        */
        CHILD_OF("child_of"),

        /**
        * <p>The parent Span doesn't depend in any way on the result of the child Span</p>
        */
        FOLLOWS_FROM("follows_from"),
    }
}
