package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'other'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object OtherAttributes {
  

    /**
    * <p>Deprecated, use <c>db.client.connection.state</c> instead.</p>
    */
    @Deprecated("Replaced by `db.client.connection.state`.")
    const val STATE: String = "state"

    /**
    * <p>STATE</p>
    */
    @Deprecated("Replaced by `db.client.connection.state`.")
    enum class StateValues(val value: String) {

        /**
        * <p>idle.</p>
        */
        IDLE("idle"),

        /**
        * <p>used.</p>
        */
        USED("used"),
    }
}
