package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'peer'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object PeerAttributes {
  

    /**
    * <p>The <a href="/docs/resource/README.md#service"><c>service.name</c></a> of the remote service. SHOULD be equal to the actual <c>service.name</c> resource attribute of the remote service if any.</p>
    */
    @IncubatingApi
    const val PEER_SERVICE: String = "peer.service"
}
