package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'security_rule'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object SecurityRuleAttributes {
  

    /**
    * <p>A categorization value keyword used by the entity using the rule for detection of this event</p>
    */
    @IncubatingApi
    const val SECURITY_RULE_CATEGORY: String = "security_rule.category"

    /**
    * <p>The description of the rule generating the event.</p>
    */
    @IncubatingApi
    const val SECURITY_RULE_DESCRIPTION: String = "security_rule.description"

    /**
    * <p>Name of the license under which the rule used to generate this event is made available.</p>
    */
    @IncubatingApi
    const val SECURITY_RULE_LICENSE: String = "security_rule.license"

    /**
    * <p>The name of the rule or signature generating the event.</p>
    */
    @IncubatingApi
    const val SECURITY_RULE_NAME: String = "security_rule.name"

    /**
    * <p>Reference URL to additional information about the rule used to generate this event.</p>
    * <p>Notes:</p>
    * <p>The URL can point to the vendor’s documentation about the rule. If that’s not available, it can also be a link to a more general page describing this type of alert.</p>
    */
    @IncubatingApi
    const val SECURITY_RULE_REFERENCE: String = "security_rule.reference"

    /**
    * <p>Name of the ruleset, policy, group, or parent category in which the rule used to generate this event is a member.</p>
    */
    @IncubatingApi
    const val SECURITY_RULE_RULESET_NAME: String = "security_rule.ruleset.name"

    /**
    * <p>A rule ID that is unique within the scope of a set or group of agents, observers, or other entities using the rule for detection of this event.</p>
    */
    @IncubatingApi
    const val SECURITY_RULE_UUID: String = "security_rule.uuid"

    /**
    * <p>The version / revision of the rule being used for analysis.</p>
    */
    @IncubatingApi
    const val SECURITY_RULE_VERSION: String = "security_rule.version"
}
