package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'session'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object SessionAttributes {
  

    /**
    * <p>A unique id to identify a session.</p>
    */
    @IncubatingApi
    const val SESSION_ID: String = "session.id"

    /**
    * <p>The previous <c>session.id</c> for this user, when known.</p>
    */
    @IncubatingApi
    const val SESSION_PREVIOUS_ID: String = "session.previous_id"
}
