package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'source'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object SourceAttributes {
  

    /**
    * <p>Source address - domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.</p>
    * <p>Notes:</p>
    * <p>When observed from the destination side, and when communicating through an intermediary, <c>source.address</c> SHOULD represent the source address behind any intermediaries, for example proxies, if it's available.</p>
    */
    @IncubatingApi
    const val SOURCE_ADDRESS: String = "source.address"

    /**
    * <p>Source port number</p>
    */
    @IncubatingApi
    const val SOURCE_PORT: String = "source.port"
}
