package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'user'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object UserAttributes {
  

    /**
    * <p>User email address.</p>
    */
    @IncubatingApi
    const val USER_EMAIL: String = "user.email"

    /**
    * <p>User's full name</p>
    */
    @IncubatingApi
    const val USER_FULL_NAME: String = "user.full_name"

    /**
    * <p>Unique user hash to correlate information for a user in anonymized form.</p>
    * <p>Notes:</p>
    * <p>Useful if <c>user.id</c> or <c>user.name</c> contain confidential information and cannot be used.</p>
    */
    @IncubatingApi
    const val USER_HASH: String = "user.hash"

    /**
    * <p>Unique identifier of the user.</p>
    */
    @IncubatingApi
    const val USER_ID: String = "user.id"

    /**
    * <p>Short name or login/username of the user.</p>
    */
    @IncubatingApi
    const val USER_NAME: String = "user.name"

    /**
    * <p>Array of user roles at the time of the event.</p>
    */
    @IncubatingApi
    const val USER_ROLES: String = "user.roles"
}
