package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'app'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object AppAttributes {
  

    /**
    * <p>Unique identifier for a particular build or compilation of the application.</p>
    */
    @IncubatingApi
    const val APP_BUILD_ID: String = "app.build_id"

    /**
    * <p>A unique identifier representing the installation of an application on a specific device</p>
    * <p>Notes:</p>
    * <p>Its value SHOULD persist across launches of the same application installation, including through application upgrades.
    * It SHOULD change if the application is uninstalled or if all applications of the vendor are uninstalled.
    * Additionally, users might be able to reset this value (e.g. by clearing application data).
    * If an app is installed multiple times on the same device (e.g. in different accounts on Android), each <c>app.installation.id</c> SHOULD have a different value.
    * If multiple OpenTelemetry SDKs are used within the same application, they SHOULD use the same value for <c>app.installation.id</c>.
    * Hardware IDs (e.g. serial number, IMEI, MAC address) MUST NOT be used as the <c>app.installation.id</c>.</p>
    * <p>For iOS, this value SHOULD be equal to the <a href="https://developer.apple.com/documentation/uikit/uidevice/identifierforvendor">vendor identifier</a>.</p>
    * <p>For Android, examples of <c>app.installation.id</c> implementations include:</p>
    * <ul>
    *   <li><a href="https://firebase.google.com/docs/projects/manage-installations">Firebase Installation ID</a>.</li>
    *   <li>A globally unique UUID which is persisted across sessions in your application.</li>
    *   <li><a href="https://developer.android.com/identity/app-set-id">App set ID</a>.</li>
    *   <li><a href="https://developer.android.com/reference/android/provider/Settings.Secure#ANDROID_ID"><c>Settings.getString(Settings.Secure.ANDROID_ID)</c></a>.</li>
    * </ul>
    * <p>More information about Android identifier best practices can be found in the <a href="https://developer.android.com/training/articles/user-data-ids">Android user data IDs guide</a>.</p>
    */
    @IncubatingApi
    const val APP_INSTALLATION_ID: String = "app.installation.id"

    /**
    * <p>A number of frame renders that experienced jank.</p>
    * <p>Notes:</p>
    * <p>Depending on platform limitations, the value provided MAY be approximation.</p>
    */
    @IncubatingApi
    const val APP_JANK_FRAME_COUNT: String = "app.jank.frame_count"

    /**
    * <p>The time period, in seconds, for which this jank is being reported.</p>
    */
    @IncubatingApi
    const val APP_JANK_PERIOD: String = "app.jank.period"

    /**
    * <p>The minimum rendering threshold for this jank, in seconds.</p>
    */
    @IncubatingApi
    const val APP_JANK_THRESHOLD: String = "app.jank.threshold"

    /**
    * <p>The x (horizontal) coordinate of a screen coordinate, in screen pixels.</p>
    */
    @IncubatingApi
    const val APP_SCREEN_COORDINATE_X: String = "app.screen.coordinate.x"

    /**
    * <p>The y (vertical) component of a screen coordinate, in screen pixels.</p>
    */
    @IncubatingApi
    const val APP_SCREEN_COORDINATE_Y: String = "app.screen.coordinate.y"

    /**
    * <p>An identifier that uniquely differentiates this screen from other screens in the same application.</p>
    * <p>Notes:</p>
    * <p>A screen represents only the part of the device display drawn by the app. It typically contains multiple widgets or UI components and is larger in scope than individual widgets. Multiple screens can coexist on the same display simultaneously (e.g., split view on tablets).</p>
    */
    @IncubatingApi
    const val APP_SCREEN_ID: String = "app.screen.id"

    /**
    * <p>The name of an application screen.</p>
    * <p>Notes:</p>
    * <p>A screen represents only the part of the device display drawn by the app. It typically contains multiple widgets or UI components and is larger in scope than individual widgets. Multiple screens can coexist on the same display simultaneously (e.g., split view on tablets).</p>
    */
    @IncubatingApi
    const val APP_SCREEN_NAME: String = "app.screen.name"

    /**
    * <p>An identifier that uniquely differentiates this widget from other widgets in the same application.</p>
    * <p>Notes:</p>
    * <p>A widget is an application component, typically an on-screen visual GUI element.</p>
    */
    @IncubatingApi
    const val APP_WIDGET_ID: String = "app.widget.id"

    /**
    * <p>The name of an application widget.</p>
    * <p>Notes:</p>
    * <p>A widget is an application component, typically an on-screen visual GUI element.</p>
    */
    @IncubatingApi
    const val APP_WIDGET_NAME: String = "app.widget.name"
}
