package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'azure'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object AzureAttributes {
  

    /**
    * <p>The unique identifier of the client instance.</p>
    */
    @IncubatingApi
    const val AZURE_CLIENT_ID: String = "azure.client.id"

    /**
    * <p>Cosmos client connection mode.</p>
    */
    @IncubatingApi
    const val AZURE_COSMOSDB_CONNECTION_MODE: String = "azure.cosmosdb.connection.mode"

    /**
    * <p>Account or request <a href="https://learn.microsoft.com/azure/cosmos-db/consistency-levels">consistency level</a>.</p>
    */
    @IncubatingApi
    const val AZURE_COSMOSDB_CONSISTENCY_LEVEL: String = "azure.cosmosdb.consistency.level"

    /**
    * <p>List of regions contacted during operation in the order that they were contacted. If there is more than one region listed, it indicates that the operation was performed on multiple regions i.e. cross-regional call.</p>
    * <p>Notes:</p>
    * <p>Region name matches the format of <c>displayName</c> in <a href="https://learn.microsoft.com/rest/api/resources/subscriptions/list-locations">Azure Location API</a></p>
    */
    @IncubatingApi
    const val AZURE_COSMOSDB_OPERATION_CONTACTED_REGIONS: String = "azure.cosmosdb.operation.contacted_regions"

    /**
    * <p>The number of request units consumed by the operation.</p>
    */
    @IncubatingApi
    const val AZURE_COSMOSDB_OPERATION_REQUEST_CHARGE: String = "azure.cosmosdb.operation.request_charge"

    /**
    * <p>Request payload size in bytes.</p>
    */
    @IncubatingApi
    const val AZURE_COSMOSDB_REQUEST_BODY_SIZE: String = "azure.cosmosdb.request.body.size"

    /**
    * <p>Cosmos DB sub status code.</p>
    */
    @IncubatingApi
    const val AZURE_COSMOSDB_RESPONSE_SUB_STATUS_CODE: String = "azure.cosmosdb.response.sub_status_code"

    /**
    * <p><a href="https://learn.microsoft.com/azure/azure-resource-manager/management/azure-services-resource-providers">Azure Resource Provider Namespace</a> as recognized by the client.</p>
    */
    @IncubatingApi
    const val AZURE_RESOURCE_PROVIDER_NAMESPACE: String = "azure.resource_provider.namespace"

    /**
    * <p>The unique identifier of the service request. It's generated by the Azure service and returned with the response.</p>
    */
    @IncubatingApi
    const val AZURE_SERVICE_REQUEST_ID: String = "azure.service.request.id"

    /**
    * <p>AZURE_COSMOSDB_CONNECTION_MODE</p>
    */
    @IncubatingApi
    enum class AzureCosmosdbConnectionModeValues(val value: String) {

        /**
        * <p>Gateway (HTTP) connection.</p>
        */
        GATEWAY("gateway"),

        /**
        * <p>Direct connection.</p>
        */
        DIRECT("direct"),
    }

    /**
    * <p>AZURE_COSMOSDB_CONSISTENCY_LEVEL</p>
    */
    @IncubatingApi
    enum class AzureCosmosdbConsistencyLevelValues(val value: String) {

        /**
        * <p>Strong</p>
        */
        STRONG("Strong"),

        /**
        * <p>Bounded Staleness</p>
        */
        BOUNDED_STALENESS("BoundedStaleness"),

        /**
        * <p>Session</p>
        */
        SESSION("Session"),

        /**
        * <p>Eventual</p>
        */
        EVENTUAL("Eventual"),

        /**
        * <p>Consistent Prefix</p>
        */
        CONSISTENT_PREFIX("ConsistentPrefix"),
    }
}
