package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'cloud'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object CloudAttributes {
  

    /**
    * <p>The cloud account ID the resource is assigned to.</p>
    */
    @IncubatingApi
    const val CLOUD_ACCOUNT_ID: String = "cloud.account.id"

    /**
    * <p>Cloud regions often have multiple, isolated locations known as zones to increase availability. Availability zone represents the zone where the resource is running.</p>
    * <p>Notes:</p>
    * <p>Availability zones are called "zones" on Alibaba Cloud and Google Cloud.</p>
    */
    @IncubatingApi
    const val CLOUD_AVAILABILITY_ZONE: String = "cloud.availability_zone"

    /**
    * <p>The cloud platform in use.</p>
    * <p>Notes:</p>
    * <p>The prefix of the service SHOULD match the one specified in <c>cloud.provider</c>.</p>
    */
    @IncubatingApi
    const val CLOUD_PLATFORM: String = "cloud.platform"

    /**
    * <p>Name of the cloud provider.</p>
    */
    @IncubatingApi
    const val CLOUD_PROVIDER: String = "cloud.provider"

    /**
    * <p>The geographical region within a cloud provider. When associated with a resource, this attribute specifies the region where the resource operates. When calling services or APIs deployed on a cloud, this attribute identifies the region where the called destination is deployed.</p>
    * <p>Notes:</p>
    * <p>Refer to your provider's docs to see the available regions, for example <a href="https://www.alibabacloud.com/help/doc-detail/40654.htm">Alibaba Cloud regions</a>, <a href="https://aws.amazon.com/about-aws/global-infrastructure/regions_az/">AWS regions</a>, <a href="https://azure.microsoft.com/global-infrastructure/geographies/">Azure regions</a>, <a href="https://cloud.google.com/about/locations">Google Cloud regions</a>, or <a href="https://www.tencentcloud.com/document/product/213/6091">Tencent Cloud regions</a>.</p>
    */
    @IncubatingApi
    const val CLOUD_REGION: String = "cloud.region"

    /**
    * <p>Cloud provider-specific native identifier of the monitored cloud resource (e.g. an <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">ARN</a> on AWS, a <a href="https://learn.microsoft.com/rest/api/resources/resources/get-by-id">fully qualified resource ID</a> on Azure, a <a href="https://google.aip.dev/122#full-resource-names">full resource name</a> on GCP)</p>
    * <p>Notes:</p>
    * <p>On some cloud providers, it may not be possible to determine the full ID at startup,
    * so it may be necessary to set <c>cloud.resource_id</c> as a span attribute instead.</p>
    * <p>The exact value to use for <c>cloud.resource_id</c> depends on the cloud provider.
    * The following well-known definitions MUST be used if you set this attribute and they apply:</p>
    * <ul>
    *   <li><strong>AWS Lambda:</strong> The function <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">ARN</a>.
    * Take care not to use the "invoked ARN" directly but replace any
    * <a href="https://docs.aws.amazon.com/lambda/latest/dg/configuration-aliases.html">alias suffix</a>
    * with the resolved function version, as the same runtime instance may be invocable with
    * multiple different aliases.</li>
    *   <li><strong>GCP:</strong> The <a href="https://cloud.google.com/iam/docs/full-resource-names">URI of the resource</a></li>
    *   <li><strong>Azure:</strong> The <a href="https://learn.microsoft.com/rest/api/resources/resources/get-by-id">Fully Qualified Resource ID</a> of the invoked function,
    * <em>not</em> the function app, having the form
    * <c>/subscriptions/<SUBSCRIPTION_GUID>/resourceGroups/<RG>/providers/Microsoft.Web/sites/<FUNCAPP>/functions/<FUNC></c>.
    * This means that a span attribute MUST be used, as an Azure function app can host multiple functions that would usually share
    * a TracerProvider.</li>
    * </ul>
    */
    @IncubatingApi
    const val CLOUD_RESOURCE_ID: String = "cloud.resource_id"

    /**
    * <p>CLOUD_PLATFORM</p>
    */
    @IncubatingApi
    enum class CloudPlatformValues(val value: String) {

        /**
        * <p>Akamai Cloud Compute</p>
        */
        AKAMAI_CLOUD_COMPUTE("akamai_cloud.compute"),

        /**
        * <p>Alibaba Cloud Elastic Compute Service</p>
        */
        ALIBABA_CLOUD_ECS("alibaba_cloud_ecs"),

        /**
        * <p>Alibaba Cloud Function Compute</p>
        */
        ALIBABA_CLOUD_FC("alibaba_cloud_fc"),

        /**
        * <p>Red Hat OpenShift on Alibaba Cloud</p>
        */
        ALIBABA_CLOUD_OPENSHIFT("alibaba_cloud_openshift"),

        /**
        * <p>AWS Elastic Compute Cloud</p>
        */
        AWS_EC2("aws_ec2"),

        /**
        * <p>AWS Elastic Container Service</p>
        */
        AWS_ECS("aws_ecs"),

        /**
        * <p>AWS Elastic Kubernetes Service</p>
        */
        AWS_EKS("aws_eks"),

        /**
        * <p>AWS Lambda</p>
        */
        AWS_LAMBDA("aws_lambda"),

        /**
        * <p>AWS Elastic Beanstalk</p>
        */
        AWS_ELASTIC_BEANSTALK("aws_elastic_beanstalk"),

        /**
        * <p>AWS App Runner</p>
        */
        AWS_APP_RUNNER("aws_app_runner"),

        /**
        * <p>Red Hat OpenShift on AWS (ROSA)</p>
        */
        AWS_OPENSHIFT("aws_openshift"),

        /**
        * <p>Azure Virtual Machines</p>
        */
        AZURE_VM("azure.vm"),

        /**
        * <p>Azure Container Apps</p>
        */
        AZURE_CONTAINER_APPS("azure.container_apps"),

        /**
        * <p>Azure Container Instances</p>
        */
        AZURE_CONTAINER_INSTANCES("azure.container_instances"),

        /**
        * <p>Azure Kubernetes Service</p>
        */
        AZURE_AKS("azure.aks"),

        /**
        * <p>Azure Functions</p>
        */
        AZURE_FUNCTIONS("azure.functions"),

        /**
        * <p>Azure App Service</p>
        */
        AZURE_APP_SERVICE("azure.app_service"),

        /**
        * <p>Azure Red Hat OpenShift</p>
        */
        AZURE_OPENSHIFT("azure.openshift"),

        /**
        * <p>Google Vertex AI Agent Engine</p>
        */
        GCP_AGENT_ENGINE("gcp.agent_engine"),

        /**
        * <p>Google Bare Metal Solution (BMS)</p>
        */
        GCP_BARE_METAL_SOLUTION("gcp_bare_metal_solution"),

        /**
        * <p>Google Cloud Compute Engine (GCE)</p>
        */
        GCP_COMPUTE_ENGINE("gcp_compute_engine"),

        /**
        * <p>Google Cloud Run</p>
        */
        GCP_CLOUD_RUN("gcp_cloud_run"),

        /**
        * <p>Google Cloud Kubernetes Engine (GKE)</p>
        */
        GCP_KUBERNETES_ENGINE("gcp_kubernetes_engine"),

        /**
        * <p>Google Cloud Functions (GCF)</p>
        */
        GCP_CLOUD_FUNCTIONS("gcp_cloud_functions"),

        /**
        * <p>Google Cloud App Engine (GAE)</p>
        */
        GCP_APP_ENGINE("gcp_app_engine"),

        /**
        * <p>Red Hat OpenShift on Google Cloud</p>
        */
        GCP_OPENSHIFT("gcp_openshift"),

        /**
        * <p>Server on Hetzner Cloud</p>
        */
        HETZNER_CLOUD_SERVER("hetzner.cloud_server"),

        /**
        * <p>Red Hat OpenShift on IBM Cloud</p>
        */
        IBM_CLOUD_OPENSHIFT("ibm_cloud_openshift"),

        /**
        * <p>Compute on Oracle Cloud Infrastructure (OCI)</p>
        */
        ORACLE_CLOUD_COMPUTE("oracle_cloud_compute"),

        /**
        * <p>Kubernetes Engine (OKE) on Oracle Cloud Infrastructure (OCI)</p>
        */
        ORACLE_CLOUD_OKE("oracle_cloud_oke"),

        /**
        * <p>Tencent Cloud Cloud Virtual Machine (CVM)</p>
        */
        TENCENT_CLOUD_CVM("tencent_cloud_cvm"),

        /**
        * <p>Tencent Cloud Elastic Kubernetes Service (EKS)</p>
        */
        TENCENT_CLOUD_EKS("tencent_cloud_eks"),

        /**
        * <p>Tencent Cloud Serverless Cloud Function (SCF)</p>
        */
        TENCENT_CLOUD_SCF("tencent_cloud_scf"),

        /**
        * <p>Vultr Cloud Compute</p>
        */
        VULTR_CLOUD_COMPUTE("vultr.cloud_compute"),
    }

    /**
    * <p>CLOUD_PROVIDER</p>
    */
    @IncubatingApi
    enum class CloudProviderValues(val value: String) {

        /**
        * <p>Akamai Cloud</p>
        */
        AKAMAI_CLOUD("akamai_cloud"),

        /**
        * <p>Alibaba Cloud</p>
        */
        ALIBABA_CLOUD("alibaba_cloud"),

        /**
        * <p>Amazon Web Services</p>
        */
        AWS("aws"),

        /**
        * <p>Microsoft Azure</p>
        */
        AZURE("azure"),

        /**
        * <p>Google Cloud Platform</p>
        */
        GCP("gcp"),

        /**
        * <p>Heroku Platform as a Service</p>
        */
        HEROKU("heroku"),

        /**
        * <p>Hetzner</p>
        */
        HETZNER("hetzner"),

        /**
        * <p>IBM Cloud</p>
        */
        IBM_CLOUD("ibm_cloud"),

        /**
        * <p>Oracle Cloud Infrastructure (OCI)</p>
        */
        ORACLE_CLOUD("oracle_cloud"),

        /**
        * <p>Tencent Cloud</p>
        */
        TENCENT_CLOUD("tencent_cloud"),

        /**
        * <p>Vultr</p>
        */
        VULTR("vultr"),
    }
}
