package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'container'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object ContainerAttributes {

    /**
    * <p>Deprecated, use <c>cpu.mode</c> instead.</p>
    */
    @Deprecated("Replaced by `cpu.mode`.")
    const val CONTAINER_CPU_STATE: String = "container.cpu.state"

    /**
    * <p>Deprecated, use <c>container.label</c> instead.</p>
    */
    @Deprecated("Replaced by `container.label`.")
    const val CONTAINER_LABELS: String = "container.labels"

    /**
    * <p>The container runtime managing this container.</p>
    */
    @Deprecated("Replaced by `container.runtime.name`.")
    const val CONTAINER_RUNTIME: String = "container.runtime"

    /**
    * <p>CONTAINER_CPU_STATE</p>
    */
    @Deprecated("Replaced by `cpu.mode`.")
    enum class ContainerCpuStateValues(val value: String) {

        /**
        * <p>When tasks of the cgroup are in user mode (Linux). When all container processes are in user mode (Windows).</p>
        */
        USER("user"),

        /**
        * <p>When CPU is used by the system (host OS)</p>
        */
        SYSTEM("system"),

        /**
        * <p>When tasks of the cgroup are in kernel mode (Linux). When all container processes are in kernel mode (Windows).</p>
        */
        KERNEL("kernel"),
    }
}
