package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'device'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object DeviceAttributes {
  

    /**
    * <p>A unique identifier representing the device</p>
    * <p>Notes:</p>
    * <p>Its value SHOULD be identical for all apps on a device and it SHOULD NOT change if an app is uninstalled and re-installed.
    * However, it might be resettable by the user for all apps on a device.
    * Hardware IDs (e.g. vendor-specific serial number, IMEI or MAC address) MAY be used as values.</p>
    * <p>More information about Android identifier best practices can be found in the <a href="https://developer.android.com/training/articles/user-data-ids">Android user data IDs guide</a>.</p>
    * <blockquote>
    * <p>[!WARNING]</p>
    * <p>This attribute may contain sensitive (PII) information. Caution should be taken when storing personal data or anything which can identify a user. GDPR and data protection laws may apply,
    * ensure you do your own due diligence.</p>
    * <p>Due to these reasons, this identifier is not recommended for consumer applications and will likely result in rejection from both Google Play and App Store.
    * However, it may be appropriate for specific enterprise scenarios, such as kiosk devices or enterprise-managed devices, with appropriate compliance clearance.
    * Any instrumentation providing this identifier MUST implement it as an opt-in feature.</p>
    * <p>See <a href="/docs/registry/attributes/app.md#app-installation-id"><c>app.installation.id</c></a> for a more privacy-preserving alternative.</p></blockquote>
    */
    @IncubatingApi
    const val DEVICE_ID: String = "device.id"

    /**
    * <p>The name of the device manufacturer</p>
    * <p>Notes:</p>
    * <p>The Android OS provides this field via <a href="https://developer.android.com/reference/android/os/Build#MANUFACTURER">Build</a>. iOS apps SHOULD hardcode the value <c>Apple</c>.</p>
    */
    @IncubatingApi
    const val DEVICE_MANUFACTURER: String = "device.manufacturer"

    /**
    * <p>The model identifier for the device</p>
    * <p>Notes:</p>
    * <p>It's recommended this value represents a machine-readable version of the model identifier rather than the market or consumer-friendly name of the device.</p>
    */
    @IncubatingApi
    const val DEVICE_MODEL_IDENTIFIER: String = "device.model.identifier"

    /**
    * <p>The marketing name for the device model</p>
    * <p>Notes:</p>
    * <p>It's recommended this value represents a human-readable version of the device model rather than a machine-readable alternative.</p>
    */
    @IncubatingApi
    const val DEVICE_MODEL_NAME: String = "device.model.name"
}
