package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'disk'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object DiskAttributes {
  

    /**
    * <p>The disk IO operation direction.</p>
    */
    @IncubatingApi
    const val DISK_IO_DIRECTION: String = "disk.io.direction"

    /**
    * <p>DISK_IO_DIRECTION</p>
    */
    @IncubatingApi
    enum class DiskIoDirectionValues(val value: String) {

        /**
        * <p>read.</p>
        */
        READ("read"),

        /**
        * <p>write.</p>
        */
        WRITE("write"),
    }
}
