package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'dns'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object DnsAttributes {
  

    /**
    * <p>The list of IPv4 or IPv6 addresses resolved during DNS lookup.</p>
    */
    @IncubatingApi
    const val DNS_ANSWERS: String = "dns.answers"

    /**
    * <p>The name being queried.</p>
    * <p>Notes:</p>
    * <p>If the name field contains non-printable characters (below 32 or above 126), those characters should be represented as escaped base 10 integers (\DDD). Back slashes and quotes should be escaped. Tabs, carriage returns, and line feeds should be converted to \t, \r, and \n respectively.</p>
    */
    @IncubatingApi
    const val DNS_QUESTION_NAME: String = "dns.question.name"
}
