package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'dns'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object DnsAttributes {
  

    /**
    * <p>The list of IPv4 or IPv6 addresses resolved during DNS lookup.</p>
    */
    @IncubatingApi
    const val DNS_ANSWERS: String = "dns.answers"

    /**
    * <p>The name being queried.</p>
    * <p>Notes:</p>
    * <p>The name represents the queried domain name as it appears in the DNS query without any additional normalization.</p>
    */
    @IncubatingApi
    const val DNS_QUESTION_NAME: String = "dns.question.name"
}
