package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'elasticsearch'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object ElasticsearchAttributes {
  

    /**
    * <p>Represents the human-readable identifier of the node/instance to which a request was routed.</p>
    */
    @IncubatingApi
    const val ELASTICSEARCH_NODE_NAME: String = "elasticsearch.node.name"
}
