package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'event'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object EventAttributes {
  

    /**
    * <p>Identifies the class / type of event.</p>
    */
    @Deprecated("The value of this attribute MUST now be set as the value of the EventName field on the LogRecord to indicate that the LogRecord represents an Event.")
    const val EVENT_NAME: String = "event.name"
}
