package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'exception'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object ExceptionAttributes {
  

    /**
    * <p>Indicates that the exception is escaping the scope of the span.</p>
    */
    @Deprecated("It's no longer recommended to record exceptions that are handled and do not escape the scope of a span.")
    const val EXCEPTION_ESCAPED: String = "exception.escaped"

    /**
    * <p>The exception message.</p>
    * <p>Notes:</p>
    * <blockquote>
    * <p>[!WARNING]</p>
    * <p>This attribute may contain sensitive information.</p></blockquote>
    */
    const val EXCEPTION_MESSAGE: String = "exception.message"

    /**
    * <p>A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG.</p>
    */
    const val EXCEPTION_STACKTRACE: String = "exception.stacktrace"

    /**
    * <p>The type of the exception (its fully-qualified class name, if applicable). The dynamic type of the exception should be preferred over the static type in languages that support it.</p>
    * <p>Notes:</p>
    * <p>If the recorded exception type is a wrapper that is not meaningful for
    * failure classification, instrumentation MAY use the type of the inner
    * exception instead. For example, in Go, errors created with <c>fmt.Errorf</c>
    * using <c>%w</c> MAY be unwrapped when the wrapper type does not help
    * classify the failure.</p>
    */
    const val EXCEPTION_TYPE: String = "exception.type"
}
