package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'feature_flag'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object FeatureFlagAttributes {

    /**
    * <p>Deprecated, use <c>feature_flag.error.message</c> instead.</p>
    */
    @Deprecated("Replaced by `feature_flag.error.message`.")
    const val FEATURE_FLAG_EVALUATION_ERROR_MESSAGE: String = "feature_flag.evaluation.error.message"

    /**
    * <p>Deprecated, use <c>feature_flag.result.reason</c> instead.</p>
    */
    @Deprecated("Replaced by `feature_flag.result.reason`.")
    const val FEATURE_FLAG_EVALUATION_REASON: String = "feature_flag.evaluation.reason"

    /**
    * <p>Deprecated, use <c>feature_flag.result.variant</c> instead.</p>
    */
    @Deprecated("Replaced by `feature_flag.result.variant`.")
    const val FEATURE_FLAG_VARIANT: String = "feature_flag.variant"

    /**
    * <p>FEATURE_FLAG_EVALUATION_REASON</p>
    */
    @Deprecated("Replaced by `feature_flag.result.reason`.")
    enum class FeatureFlagEvaluationReasonValues(val value: String) {

        /**
        * <p>The resolved value is static (no dynamic evaluation).</p>
        */
        STATIC("static"),

        /**
        * <p>The resolved value fell back to a pre-configured value (no dynamic evaluation occurred or dynamic evaluation yielded no result).</p>
        */
        DEFAULT("default"),

        /**
        * <p>The resolved value was the result of a dynamic evaluation, such as a rule or specific user-targeting.</p>
        */
        TARGETING_MATCH("targeting_match"),

        /**
        * <p>The resolved value was the result of pseudorandom assignment.</p>
        */
        SPLIT("split"),

        /**
        * <p>The resolved value was retrieved from cache.</p>
        */
        CACHED("cached"),

        /**
        * <p>The resolved value was the result of the flag being disabled in the management system.</p>
        */
        DISABLED("disabled"),

        /**
        * <p>The reason for the resolved value could not be determined.</p>
        */
        UNKNOWN("unknown"),

        /**
        * <p>The resolved value is non-authoritative or possibly out of date</p>
        */
        STALE("stale"),

        /**
        * <p>The resolved value was the result of an error.</p>
        */
        ERROR("error"),
    }

}
