package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'gen_ai'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object GenAiAttributes {

    /**
    * <p>Deprecated, use Event API to report completions contents.</p>
    */
    @Deprecated("Removed, no replacement at this time.")
    const val GEN_AI_COMPLETION: String = "gen_ai.completion"

    /**
    * <p>Deprecated, use <c>gen_ai.output.type</c>.</p>
    */
    @Deprecated("Replaced by `gen_ai.output.type`.")
    const val GEN_AI_OPENAI_REQUEST_RESPONSE_FORMAT: String = "gen_ai.openai.request.response_format"

    /**
    * <p>Deprecated, use <c>gen_ai.request.seed</c>.</p>
    */
    @Deprecated("Replaced by `gen_ai.request.seed`.")
    const val GEN_AI_OPENAI_REQUEST_SEED: String = "gen_ai.openai.request.seed"

    /**
    * <p>Deprecated, use <c>openai.request.service_tier</c>.</p>
    */
    @Deprecated("Replaced by `openai.request.service_tier`.")
    const val GEN_AI_OPENAI_REQUEST_SERVICE_TIER: String = "gen_ai.openai.request.service_tier"

    /**
    * <p>Deprecated, use <c>openai.response.service_tier</c>.</p>
    */
    @Deprecated("Replaced by `openai.response.service_tier`.")
    const val GEN_AI_OPENAI_RESPONSE_SERVICE_TIER: String = "gen_ai.openai.response.service_tier"

    /**
    * <p>Deprecated, use <c>openai.response.system_fingerprint</c>.</p>
    */
    @Deprecated("Replaced by `openai.response.system_fingerprint`.")
    const val GEN_AI_OPENAI_RESPONSE_SYSTEM_FINGERPRINT: String = "gen_ai.openai.response.system_fingerprint"

    /**
    * <p>Deprecated, use Event API to report prompt contents.</p>
    */
    @Deprecated("Removed, no replacement at this time.")
    const val GEN_AI_PROMPT: String = "gen_ai.prompt"

    /**
    * <p>Deprecated, use <c>gen_ai.provider.name</c> instead.</p>
    */
    @Deprecated("Replaced by `gen_ai.provider.name`.")
    const val GEN_AI_SYSTEM: String = "gen_ai.system"

    /**
    * <p>Deprecated, use <c>gen_ai.usage.output_tokens</c> instead.</p>
    */
    @Deprecated("Replaced by `gen_ai.usage.output_tokens`.")
    const val GEN_AI_USAGE_COMPLETION_TOKENS: String = "gen_ai.usage.completion_tokens"

    /**
    * <p>Deprecated, use <c>gen_ai.usage.input_tokens</c> instead.</p>
    */
    @Deprecated("Replaced by `gen_ai.usage.input_tokens`.")
    const val GEN_AI_USAGE_PROMPT_TOKENS: String = "gen_ai.usage.prompt_tokens"

    /**
    * <p>GEN_AI_OPENAI_REQUEST_RESPONSE_FORMAT</p>
    */
    @Deprecated("Replaced by `gen_ai.output.type`.")
    enum class GenAiOpenaiRequestResponseFormatValues(val value: String) {

        /**
        * <p>Text response format</p>
        */
        TEXT("text"),

        /**
        * <p>JSON object response format</p>
        */
        JSON_OBJECT("json_object"),

        /**
        * <p>JSON schema response format</p>
        */
        JSON_SCHEMA("json_schema"),
    }

    /**
    * <p>GEN_AI_OPENAI_REQUEST_SERVICE_TIER</p>
    */
    @Deprecated("Replaced by `openai.request.service_tier`.")
    enum class GenAiOpenaiRequestServiceTierValues(val value: String) {

        /**
        * <p>The system will utilize scale tier credits until they are exhausted.</p>
        */
        AUTO("auto"),

        /**
        * <p>The system will utilize the default scale tier.</p>
        */
        DEFAULT("default"),
    }

    /**
    * <p>GEN_AI_SYSTEM</p>
    */
    @Deprecated("Replaced by `gen_ai.provider.name`.")
    enum class GenAiSystemValues(val value: String) {

        /**
        * <p>OpenAI</p>
        */
        OPENAI("openai"),

        /**
        * <p>Any Google generative AI endpoint</p>
        */
        GCP_GEN_AI("gcp.gen_ai"),

        /**
        * <p>Vertex AI</p>
        */
        GCP_VERTEX_AI("gcp.vertex_ai"),

        /**
        * <p>Gemini</p>
        */
        GCP_GEMINI("gcp.gemini"),

        /**
        * <p>Vertex AI</p>
        */
        VERTEX_AI("vertex_ai"),

        /**
        * <p>Gemini</p>
        */
        GEMINI("gemini"),

        /**
        * <p>Anthropic</p>
        */
        ANTHROPIC("anthropic"),

        /**
        * <p>Cohere</p>
        */
        COHERE("cohere"),

        /**
        * <p>Azure AI Inference</p>
        */
        AZ_AI_INFERENCE("az.ai.inference"),

        /**
        * <p>Azure OpenAI</p>
        */
        AZ_AI_OPENAI("az.ai.openai"),

        /**
        * <p>Azure AI Inference</p>
        */
        AZURE_AI_INFERENCE("azure.ai.inference"),

        /**
        * <p>Azure OpenAI</p>
        */
        AZURE_AI_OPENAI("azure.ai.openai"),

        /**
        * <p>IBM Watsonx AI</p>
        */
        IBM_WATSONX_AI("ibm.watsonx.ai"),

        /**
        * <p>AWS Bedrock</p>
        */
        AWS_BEDROCK("aws.bedrock"),

        /**
        * <p>Perplexity</p>
        */
        PERPLEXITY("perplexity"),

        /**
        * <p>xAI</p>
        */
        XAI("xai"),

        /**
        * <p>DeepSeek</p>
        */
        DEEPSEEK("deepseek"),

        /**
        * <p>Groq</p>
        */
        GROQ("groq"),

        /**
        * <p>Mistral AI</p>
        */
        MISTRAL_AI("mistral_ai"),
    }

}
