package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'go'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object GoAttributes {
  

    /**
    * <p>The type of memory.</p>
    */
    @IncubatingApi
    const val GO_MEMORY_TYPE: String = "go.memory.type"

    /**
    * <p>GO_MEMORY_TYPE</p>
    */
    @IncubatingApi
    enum class GoMemoryTypeValues(val value: String) {

        /**
        * <p>Memory allocated from the heap that is reserved for stack space, whether or not it is currently in-use.</p>
        */
        STACK("stack"),

        /**
        * <p>Memory used by the Go runtime, excluding other categories of memory usage described in this enumeration.</p>
        */
        OTHER("other"),
    }
}
