package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'graphql'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object GraphqlAttributes {
  

    /**
    * <p>The GraphQL document being executed.</p>
    * <p>Notes:</p>
    * <p>The value may be sanitized to exclude sensitive information.</p>
    */
    @IncubatingApi
    const val GRAPHQL_DOCUMENT: String = "graphql.document"

    /**
    * <p>The name of the operation being executed.</p>
    */
    @IncubatingApi
    const val GRAPHQL_OPERATION_NAME: String = "graphql.operation.name"

    /**
    * <p>The type of the operation being executed.</p>
    */
    @IncubatingApi
    const val GRAPHQL_OPERATION_TYPE: String = "graphql.operation.type"

    /**
    * <p>GRAPHQL_OPERATION_TYPE</p>
    */
    @IncubatingApi
    enum class GraphqlOperationTypeValues(val value: String) {

        /**
        * <p>GraphQL query</p>
        */
        QUERY("query"),

        /**
        * <p>GraphQL mutation</p>
        */
        MUTATION("mutation"),

        /**
        * <p>GraphQL subscription</p>
        */
        SUBSCRIPTION("subscription"),
    }
}
