package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'heroku'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object HerokuAttributes {
  

    /**
    * <p>Unique identifier for the application</p>
    */
    @IncubatingApi
    const val HEROKU_APP_ID: String = "heroku.app.id"

    /**
    * <p>Commit hash for the current release</p>
    */
    @IncubatingApi
    const val HEROKU_RELEASE_COMMIT: String = "heroku.release.commit"

    /**
    * <p>Time and date the release was created</p>
    */
    @IncubatingApi
    const val HEROKU_RELEASE_CREATION_TIMESTAMP: String = "heroku.release.creation_timestamp"
}
