package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'http'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object HttpAttributes {
  

    /**
    * <p>Deprecated, use <c>client.address</c> instead.</p>
    */
    @Deprecated("Replaced by `client.address`.")
    const val HTTP_CLIENT_IP: String = "http.client_ip"

    /**
    * <p>State of the HTTP connection in the HTTP connection pool.</p>
    */
    @IncubatingApi
    const val HTTP_CONNECTION_STATE: String = "http.connection.state"

    /**
    * <p>Deprecated, use <c>network.protocol.name</c> instead.</p>
    */
    @Deprecated("Replaced by `network.protocol.name`.")
    const val HTTP_FLAVOR: String = "http.flavor"

    /**
    * <p>Deprecated, use one of <c>server.address</c>, <c>client.address</c> or <c>http.request.header.host</c> instead, depending on the usage.</p>
    */
    @Deprecated("Replaced by one of `server.address`, `client.address` or `http.request.header.host`, depending on the usage.")
    const val HTTP_HOST: String = "http.host"

    /**
    * <p>Deprecated, use <c>http.request.method</c> instead.</p>
    */
    @Deprecated("Replaced by `http.request.method`.")
    const val HTTP_METHOD: String = "http.method"

    /**
    * <p>The size of the request payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the <a href="https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length">Content-Length</a> header. For requests using transport encoding, this should be the compressed size.</p>
    */
    @IncubatingApi
    const val HTTP_REQUEST_BODY_SIZE: String = "http.request.body.size"

    /**
    * <p>HTTP request headers, <c><key></c> being the normalized HTTP Header name (lowercase), the value being the header values.</p>
    * <p>Notes:</p>
    * <p>Instrumentations SHOULD require an explicit configuration of which headers are to be captured.
    * Including all request headers can be a security risk - explicit configuration helps avoid leaking sensitive information.</p>
    * <p>The <c>User-Agent</c> header is already captured in the <c>user_agent.original</c> attribute.
    * Users MAY explicitly configure instrumentations to capture them even though it is not recommended.</p>
    * <p>The attribute value MUST consist of either multiple header values as an array of strings
    * or a single-item array containing a possibly comma-concatenated string, depending on the way
    * the HTTP library provides access to headers.</p>
    * <p>Examples:</p>
    * <ul>
    *   <li>A header <c>Content-Type: application/json</c> SHOULD be recorded as the <c>http.request.header.content-type</c>
    * attribute with value <c>["application/json"]</c>.</li>
    *   <li>A header <c>X-Forwarded-For: 1.2.3.4, 1.2.3.5</c> SHOULD be recorded as the <c>http.request.header.x-forwarded-for</c>
    * attribute with value <c>["1.2.3.4", "1.2.3.5"]</c> or <c>["1.2.3.4, 1.2.3.5"]</c> depending on the HTTP library.</li>
    * </ul>
    */
    const val HTTP_REQUEST_HEADER: String = "http.request.header"

    /**
    * <p>HTTP request method.</p>
    * <p>Notes:</p>
    * <p>HTTP request method value SHOULD be "known" to the instrumentation.
    * By default, this convention defines "known" methods as the ones listed in <a href="https://www.rfc-editor.org/rfc/rfc9110.html#name-methods">RFC9110</a>
    * and the PATCH method defined in <a href="https://www.rfc-editor.org/rfc/rfc5789.html">RFC5789</a>.</p>
    * <p>If the HTTP request method is not known to instrumentation, it MUST set the <c>http.request.method</c> attribute to <c>_OTHER</c>.</p>
    * <p>If the HTTP instrumentation could end up converting valid HTTP request methods to <c>_OTHER</c>, then it MUST provide a way to override
    * the list of known HTTP methods. If this override is done via environment variable, then the environment variable MUST be named
    * OTEL_INSTRUMENTATION_HTTP_KNOWN_METHODS and support a comma-separated list of case-sensitive known HTTP methods
    * (this list MUST be a full override of the default known method, it is not a list of known methods in addition to the defaults).</p>
    * <p>HTTP method names are case-sensitive and <c>http.request.method</c> attribute value MUST match a known HTTP method name exactly.
    * Instrumentations for specific web frameworks that consider HTTP methods to be case insensitive, SHOULD populate a canonical equivalent.
    * Tracing instrumentations that do so, MUST also set <c>http.request.method_original</c> to the original value.</p>
    */
    const val HTTP_REQUEST_METHOD: String = "http.request.method"

    /**
    * <p>Original HTTP method sent by the client in the request line.</p>
    */
    const val HTTP_REQUEST_METHOD_ORIGINAL: String = "http.request.method_original"

    /**
    * <p>The ordinal number of request resending attempt (for any reason, including redirects).</p>
    * <p>Notes:</p>
    * <p>The resend count SHOULD be updated each time an HTTP request gets resent by the client, regardless of what was the cause of the resending (e.g. redirection, authorization failure, 503 Server Unavailable, network issues, or any other).</p>
    */
    const val HTTP_REQUEST_RESEND_COUNT: String = "http.request.resend_count"

    /**
    * <p>The total size of the request in bytes. This should be the total number of bytes sent over the wire, including the request line (HTTP/1.1), framing (HTTP/2 and HTTP/3), headers, and request body if any.</p>
    */
    @IncubatingApi
    const val HTTP_REQUEST_SIZE: String = "http.request.size"

    /**
    * <p>Deprecated, use <c>http.request.header.content-length</c> instead.</p>
    */
    @Deprecated("Replaced by `http.request.header.content-length`.")
    const val HTTP_REQUEST_CONTENT_LENGTH: String = "http.request_content_length"

    /**
    * <p>Deprecated, use <c>http.request.body.size</c> instead.</p>
    */
    @Deprecated("Replaced by `http.request.body.size`.")
    const val HTTP_REQUEST_CONTENT_LENGTH_UNCOMPRESSED: String = "http.request_content_length_uncompressed"

    /**
    * <p>The size of the response payload body in bytes. This is the number of bytes transferred excluding headers and is often, but not always, present as the <a href="https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length">Content-Length</a> header. For requests using transport encoding, this should be the compressed size.</p>
    */
    @IncubatingApi
    const val HTTP_RESPONSE_BODY_SIZE: String = "http.response.body.size"

    /**
    * <p>HTTP response headers, <c><key></c> being the normalized HTTP Header name (lowercase), the value being the header values.</p>
    * <p>Notes:</p>
    * <p>Instrumentations SHOULD require an explicit configuration of which headers are to be captured.
    * Including all response headers can be a security risk - explicit configuration helps avoid leaking sensitive information.</p>
    * <p>Users MAY explicitly configure instrumentations to capture them even though it is not recommended.</p>
    * <p>The attribute value MUST consist of either multiple header values as an array of strings
    * or a single-item array containing a possibly comma-concatenated string, depending on the way
    * the HTTP library provides access to headers.</p>
    * <p>Examples:</p>
    * <ul>
    *   <li>A header <c>Content-Type: application/json</c> header SHOULD be recorded as the <c>http.request.response.content-type</c>
    * attribute with value <c>["application/json"]</c>.</li>
    *   <li>A header <c>My-custom-header: abc, def</c> header SHOULD be recorded as the <c>http.response.header.my-custom-header</c>
    * attribute with value <c>["abc", "def"]</c> or <c>["abc, def"]</c> depending on the HTTP library.</li>
    * </ul>
    */
    const val HTTP_RESPONSE_HEADER: String = "http.response.header"

    /**
    * <p>The total size of the response in bytes. This should be the total number of bytes sent over the wire, including the status line (HTTP/1.1), framing (HTTP/2 and HTTP/3), headers, and response body and trailers if any.</p>
    */
    @IncubatingApi
    const val HTTP_RESPONSE_SIZE: String = "http.response.size"

    /**
    * <p><a href="https://tools.ietf.org/html/rfc7231#section-6">HTTP response status code</a>.</p>
    */
    const val HTTP_RESPONSE_STATUS_CODE: String = "http.response.status_code"

    /**
    * <p>Deprecated, use <c>http.response.header.content-length</c> instead.</p>
    */
    @Deprecated("Replaced by `http.response.header.content-length`.")
    const val HTTP_RESPONSE_CONTENT_LENGTH: String = "http.response_content_length"

    /**
    * <p>Deprecated, use <c>http.response.body.size</c> instead.</p>
    */
    @Deprecated("Replaced by `http.response.body.size`.")
    const val HTTP_RESPONSE_CONTENT_LENGTH_UNCOMPRESSED: String = "http.response_content_length_uncompressed"

    /**
    * <p>The matched route, that is, the path template in the format used by the respective server framework.</p>
    * <p>Notes:</p>
    * <p>MUST NOT be populated when this is not supported by the HTTP server framework as the route attribute should have low-cardinality and the URI path can NOT substitute it.
    * SHOULD include the <a href="/docs/http/http-spans.md#http-server-definitions">application root</a> if there is one.</p>
    */
    const val HTTP_ROUTE: String = "http.route"

    /**
    * <p>Deprecated, use <c>url.scheme</c> instead.</p>
    */
    @Deprecated("Replaced by `url.scheme`.")
    const val HTTP_SCHEME: String = "http.scheme"

    /**
    * <p>Deprecated, use <c>server.address</c> instead.</p>
    */
    @Deprecated("Replaced by `server.address`.")
    const val HTTP_SERVER_NAME: String = "http.server_name"

    /**
    * <p>Deprecated, use <c>http.response.status_code</c> instead.</p>
    */
    @Deprecated("Replaced by `http.response.status_code`.")
    const val HTTP_STATUS_CODE: String = "http.status_code"

    /**
    * <p>Deprecated, use <c>url.path</c> and <c>url.query</c> instead.</p>
    */
    @Deprecated("Split to `url.path` and `url.query`.")
    const val HTTP_TARGET: String = "http.target"

    /**
    * <p>Deprecated, use <c>url.full</c> instead.</p>
    */
    @Deprecated("Replaced by `url.full`.")
    const val HTTP_URL: String = "http.url"

    /**
    * <p>Deprecated, use <c>user_agent.original</c> instead.</p>
    */
    @Deprecated("Replaced by `user_agent.original`.")
    const val HTTP_USER_AGENT: String = "http.user_agent"

    /**
    * <p>HTTP_CONNECTION_STATE</p>
    */
    @IncubatingApi
    enum class HttpConnectionStateValues(val value: String) {

        /**
        * <p>active state.</p>
        */
        ACTIVE("active"),

        /**
        * <p>idle state.</p>
        */
        IDLE("idle"),
    }

    /**
    * <p>HTTP_FLAVOR</p>
    */
    @Deprecated("Replaced by `network.protocol.name`.")
    enum class HttpFlavorValues(val value: String) {

        /**
        * <p>HTTP/1.0</p>
        */
        HTTP_1_0("1.0"),

        /**
        * <p>HTTP/1.1</p>
        */
        HTTP_1_1("1.1"),

        /**
        * <p>HTTP/2</p>
        */
        HTTP_2_0("2.0"),

        /**
        * <p>HTTP/3</p>
        */
        HTTP_3_0("3.0"),

        /**
        * <p>SPDY protocol.</p>
        */
        SPDY("SPDY"),

        /**
        * <p>QUIC protocol.</p>
        */
        QUIC("QUIC"),
    }

    /**
    * <p>HTTP_REQUEST_METHOD</p>
    */
    enum class HttpRequestMethodValues(val value: String) {

        /**
        * <p>CONNECT method.</p>
        */
        CONNECT("CONNECT"),

        /**
        * <p>DELETE method.</p>
        */
        DELETE("DELETE"),

        /**
        * <p>GET method.</p>
        */
        GET("GET"),

        /**
        * <p>HEAD method.</p>
        */
        HEAD("HEAD"),

        /**
        * <p>OPTIONS method.</p>
        */
        OPTIONS("OPTIONS"),

        /**
        * <p>PATCH method.</p>
        */
        PATCH("PATCH"),

        /**
        * <p>POST method.</p>
        */
        POST("POST"),

        /**
        * <p>PUT method.</p>
        */
        PUT("PUT"),

        /**
        * <p>TRACE method.</p>
        */
        TRACE("TRACE"),

        /**
        * <p>Any HTTP method that the instrumentation has no prior knowledge of.</p>
        */
        OTHER("_OTHER"),
    }
}
