package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'jsonrpc'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object JsonrpcAttributes {
  

    /**
    * <p>Protocol version, as specified in the <c>jsonrpc</c> property of the request and its corresponding response.</p>
    */
    @IncubatingApi
    const val JSONRPC_PROTOCOL_VERSION: String = "jsonrpc.protocol.version"

    /**
    * <p>A string representation of the <c>id</c> property of the request and its corresponding response.</p>
    * <p>Notes:</p>
    * <p>Under the <a href="https://www.jsonrpc.org/specification">JSON-RPC specification</a>, the <c>id</c> property may be a string, number, null, or omitted entirely. When omitted, the request is treated as a notification. Using <c>null</c> is not equivalent to omitting the <c>id</c>, but it is discouraged.
    * Instrumentations SHOULD NOT capture this attribute when the <c>id</c> is <c>null</c> or omitted.</p>
    */
    @IncubatingApi
    const val JSONRPC_REQUEST_ID: String = "jsonrpc.request.id"
}
