package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'k8s'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object K8sAttributes {

    /**
    * <p>Deprecated, use <c>k8s.pod.label</c> instead.</p>
    */
    @Deprecated("Replaced by `k8s.pod.label`.")
    const val K8S_POD_LABELS: String = "k8s.pod.labels"

}
