package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'linux'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object LinuxAttributes {
  

    /**
    * <p>The Linux Slab memory state</p>
    */
    @Deprecated("Replaced by `system.memory.linux.slab.state`.")
    const val LINUX_MEMORY_SLAB_STATE: String = "linux.memory.slab.state"

    /**
    * <p>LINUX_MEMORY_SLAB_STATE</p>
    */
    @Deprecated("Replaced by `system.memory.linux.slab.state`.")
    enum class LinuxMemorySlabStateValues(val value: String) {

        /**
        * <p>reclaimable.</p>
        */
        RECLAIMABLE("reclaimable"),

        /**
        * <p>unreclaimable.</p>
        */
        UNRECLAIMABLE("unreclaimable"),
    }
}
