package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'mcp'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object McpAttributes {
  

    /**
    * <p>The name of the request or notification method.</p>
    */
    @IncubatingApi
    const val MCP_METHOD_NAME: String = "mcp.method.name"

    /**
    * <p>The <a href="https://modelcontextprotocol.io/specification/versioning">version</a> of the Model Context Protocol used.</p>
    */
    @IncubatingApi
    const val MCP_PROTOCOL_VERSION: String = "mcp.protocol.version"

    /**
    * <p>The value of the resource uri.</p>
    * <p>Notes:</p>
    * <p>This is a URI of the resource provided in the following requests or notifications: <c>resources/read</c>, <c>resources/subscribe</c>, <c>resources/unsubscribe</c>, or <c>notifications/resources/updated</c>.</p>
    */
    @IncubatingApi
    const val MCP_RESOURCE_URI: String = "mcp.resource.uri"

    /**
    * <p>Identifies <a href="https://modelcontextprotocol.io/specification/2025-06-18/basic/transports#session-management">MCP session</a>.</p>
    */
    @IncubatingApi
    const val MCP_SESSION_ID: String = "mcp.session.id"

    /**
    * <p>MCP_METHOD_NAME</p>
    */
    @IncubatingApi
    enum class McpMethodNameValues(val value: String) {

        /**
        * <p>Notification cancelling a previously-issued request.</p>
        */
        NOTIFICATIONS_CANCELLED("notifications/cancelled"),

        /**
        * <p>Request to initialize the MCP client.</p>
        */
        INITIALIZE("initialize"),

        /**
        * <p>Notification indicating that the MCP client has been initialized.</p>
        */
        NOTIFICATIONS_INITIALIZED("notifications/initialized"),

        /**
        * <p>Notification indicating the progress for a long-running operation.</p>
        */
        NOTIFICATIONS_PROGRESS("notifications/progress"),

        /**
        * <p>Request to check that the other party is still alive.</p>
        */
        PING("ping"),

        /**
        * <p>Request to list resources available on server.</p>
        */
        RESOURCES_LIST("resources/list"),

        /**
        * <p>Request to list resource templates available on server.</p>
        */
        RESOURCES_TEMPLATES_LIST("resources/templates/list"),

        /**
        * <p>Request to read a resource.</p>
        */
        RESOURCES_READ("resources/read"),

        /**
        * <p>Notification indicating that the list of resources has changed.</p>
        */
        NOTIFICATIONS_RESOURCES_LIST_CHANGED("notifications/resources/list_changed"),

        /**
        * <p>Request to subscribe to a resource.</p>
        */
        RESOURCES_SUBSCRIBE("resources/subscribe"),

        /**
        * <p>Request to unsubscribe from resource updates.</p>
        */
        RESOURCES_UNSUBSCRIBE("resources/unsubscribe"),

        /**
        * <p>Notification indicating that a resource has been updated.</p>
        */
        NOTIFICATIONS_RESOURCES_UPDATED("notifications/resources/updated"),

        /**
        * <p>Request to list prompts available on server.</p>
        */
        PROMPTS_LIST("prompts/list"),

        /**
        * <p>Request to get a prompt.</p>
        */
        PROMPTS_GET("prompts/get"),

        /**
        * <p>Notification indicating that the list of prompts has changed.</p>
        */
        NOTIFICATIONS_PROMPTS_LIST_CHANGED("notifications/prompts/list_changed"),

        /**
        * <p>Request to list tools available on server.</p>
        */
        TOOLS_LIST("tools/list"),

        /**
        * <p>Request to call a tool.</p>
        */
        TOOLS_CALL("tools/call"),

        /**
        * <p>Notification indicating that the list of tools has changed.</p>
        */
        NOTIFICATIONS_TOOLS_LIST_CHANGED("notifications/tools/list_changed"),

        /**
        * <p>Request to set the logging level.</p>
        */
        LOGGING_SET_LEVEL("logging/setLevel"),

        /**
        * <p>Notification indicating that a message has been received.</p>
        */
        NOTIFICATIONS_MESSAGE("notifications/message"),

        /**
        * <p>Request to create a sampling message.</p>
        */
        SAMPLING_CREATE_MESSAGE("sampling/createMessage"),

        /**
        * <p>Request to complete a prompt.</p>
        */
        COMPLETION_COMPLETE("completion/complete"),

        /**
        * <p>Request to list roots available on server.</p>
        */
        ROOTS_LIST("roots/list"),

        /**
        * <p>Notification indicating that the list of roots has changed.</p>
        */
        NOTIFICATIONS_ROOTS_LIST_CHANGED("notifications/roots/list_changed"),

        /**
        * <p>Request from the server to elicit additional information from the user via the client</p>
        */
        ELICITATION_CREATE("elicitation/create"),
    }
}
