package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'message'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object MessageAttributes {
  

    /**
    * <p>Deprecated, no replacement at this time.</p>
    */
    @Deprecated("Deprecated, no replacement at this time.")
    const val MESSAGE_COMPRESSED_SIZE: String = "message.compressed_size"

    /**
    * <p>Deprecated, no replacement at this time.</p>
    */
    @Deprecated("Deprecated, no replacement at this time.")
    const val MESSAGE_ID: String = "message.id"

    /**
    * <p>Deprecated, no replacement at this time.</p>
    */
    @Deprecated("Deprecated, no replacement at this time.")
    const val MESSAGE_TYPE: String = "message.type"

    /**
    * <p>Deprecated, no replacement at this time.</p>
    */
    @Deprecated("Deprecated, no replacement at this time.")
    const val MESSAGE_UNCOMPRESSED_SIZE: String = "message.uncompressed_size"

    /**
    * <p>MESSAGE_TYPE</p>
    */
    @Deprecated("Deprecated, no replacement at this time.")
    enum class MessageTypeValues(val value: String) {

        /**
        * <p>sent.</p>
        */
        SENT("SENT"),

        /**
        * <p>received.</p>
        */
        RECEIVED("RECEIVED"),
    }
}
