package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'message'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object MessageAttributes {
  

    /**
    * <p>Deprecated, use <c>rpc.message.compressed_size</c> instead.</p>
    */
    @Deprecated("Replaced by `rpc.message.compressed_size`.")
    const val MESSAGE_COMPRESSED_SIZE: String = "message.compressed_size"

    /**
    * <p>Deprecated, use <c>rpc.message.id</c> instead.</p>
    */
    @Deprecated("Replaced by `rpc.message.id`.")
    const val MESSAGE_ID: String = "message.id"

    /**
    * <p>Deprecated, use <c>rpc.message.type</c> instead.</p>
    */
    @Deprecated("Replaced by `rpc.message.type`.")
    const val MESSAGE_TYPE: String = "message.type"

    /**
    * <p>Deprecated, use <c>rpc.message.uncompressed_size</c> instead.</p>
    */
    @Deprecated("Replaced by `rpc.message.uncompressed_size`.")
    const val MESSAGE_UNCOMPRESSED_SIZE: String = "message.uncompressed_size"

    /**
    * <p>MESSAGE_TYPE</p>
    */
    @Deprecated("Replaced by `rpc.message.type`.")
    enum class MessageTypeValues(val value: String) {

        /**
        * <p>sent.</p>
        */
        SENT("SENT"),

        /**
        * <p>received.</p>
        */
        RECEIVED("RECEIVED"),
    }
}
