package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'network'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object NetworkAttributes {

    /**
    * <p>Local address of the network connection - IP address or Unix domain socket name.</p>
    */
    const val NETWORK_LOCAL_ADDRESS: String = "network.local.address"

    /**
    * <p>Local port number of the network connection.</p>
    */
    const val NETWORK_LOCAL_PORT: String = "network.local.port"

    /**
    * <p>Peer address of the network connection - IP address or Unix domain socket name.</p>
    */
    const val NETWORK_PEER_ADDRESS: String = "network.peer.address"

    /**
    * <p>Peer port number of the network connection.</p>
    */
    const val NETWORK_PEER_PORT: String = "network.peer.port"

    /**
    * <p><a href="https://wikipedia.org/wiki/Application_layer">OSI application layer</a> or non-OSI equivalent.</p>
    * <p>Notes:</p>
    * <p>The value SHOULD be normalized to lowercase.</p>
    */
    const val NETWORK_PROTOCOL_NAME: String = "network.protocol.name"

    /**
    * <p>The actual version of the protocol used for network communication.</p>
    * <p>Notes:</p>
    * <p>If protocol version is subject to negotiation (for example using <a href="https://www.rfc-editor.org/rfc/rfc7301.html">ALPN</a>), this attribute SHOULD be set to the negotiated version. If the actual protocol version is not known, this attribute SHOULD NOT be set.</p>
    */
    const val NETWORK_PROTOCOL_VERSION: String = "network.protocol.version"

    /**
    * <p><a href="https://wikipedia.org/wiki/Transport_layer">OSI transport layer</a> or <a href="https://wikipedia.org/wiki/Inter-process_communication">inter-process communication method</a>.</p>
    * <p>Notes:</p>
    * <p>The value SHOULD be normalized to lowercase.</p>
    * <p>Consider always setting the transport when setting a port number, since
    * a port number is ambiguous without knowing the transport. For example
    * different processes could be listening on TCP port 12345 and UDP port 12345.</p>
    */
    const val NETWORK_TRANSPORT: String = "network.transport"

    /**
    * <p><a href="https://wikipedia.org/wiki/Network_layer">OSI network layer</a> or non-OSI equivalent.</p>
    * <p>Notes:</p>
    * <p>The value SHOULD be normalized to lowercase.</p>
    */
    const val NETWORK_TYPE: String = "network.type"

    /**
    * <p>NETWORK_TRANSPORT</p>
    */
    enum class NetworkTransportValues(val value: String) {

        /**
        * <p>TCP</p>
        */
        TCP("tcp"),

        /**
        * <p>UDP</p>
        */
        UDP("udp"),

        /**
        * <p>Named or anonymous pipe.</p>
        */
        PIPE("pipe"),

        /**
        * <p>Unix domain socket</p>
        */
        UNIX("unix"),

        /**
        * <p>QUIC</p>
        */
        QUIC("quic"),
    }

    /**
    * <p>NETWORK_TYPE</p>
    */
    enum class NetworkTypeValues(val value: String) {

        /**
        * <p>IPv4</p>
        */
        IPV4("ipv4"),

        /**
        * <p>IPv6</p>
        */
        IPV6("ipv6"),
    }
}
