package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'nfs'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object NfsAttributes {
  

    /**
    * <p>NFSv4+ operation name.</p>
    */
    @IncubatingApi
    const val NFS_OPERATION_NAME: String = "nfs.operation.name"

    /**
    * <p>Linux: one of "hit" (NFSD_STATS_RC_HITS), "miss" (NFSD_STATS_RC_MISSES), or "nocache" (NFSD_STATS_RC_NOCACHE -- uncacheable)</p>
    */
    @IncubatingApi
    const val NFS_SERVER_REPCACHE_STATUS: String = "nfs.server.repcache.status"
}
