package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'nodejs'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object NodejsAttributes {
  

    /**
    * <p>The state of event loop time.</p>
    */
    @IncubatingApi
    const val NODEJS_EVENTLOOP_STATE: String = "nodejs.eventloop.state"

    /**
    * <p>NODEJS_EVENTLOOP_STATE</p>
    */
    @IncubatingApi
    enum class NodejsEventloopStateValues(val value: String) {

        /**
        * <p>Active time.</p>
        */
        ACTIVE("active"),

        /**
        * <p>Idle time.</p>
        */
        IDLE("idle"),
    }
}
