package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'onc_rpc'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object OncRpcAttributes {
  

    /**
    * <p>ONC/Sun RPC procedure name.</p>
    */
    @IncubatingApi
    const val ONC_RPC_PROCEDURE_NAME: String = "onc_rpc.procedure.name"

    /**
    * <p>ONC/Sun RPC procedure number.</p>
    */
    @IncubatingApi
    const val ONC_RPC_PROCEDURE_NUMBER: String = "onc_rpc.procedure.number"

    /**
    * <p>ONC/Sun RPC program name.</p>
    */
    @IncubatingApi
    const val ONC_RPC_PROGRAM_NAME: String = "onc_rpc.program.name"

    /**
    * <p>ONC/Sun RPC program version.</p>
    */
    @IncubatingApi
    const val ONC_RPC_VERSION: String = "onc_rpc.version"
}
