package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'openai'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object OpenaiAttributes {
  

    /**
    * <p>The type of OpenAI API being used.</p>
    */
    @IncubatingApi
    const val OPENAI_API_TYPE: String = "openai.api.type"

    /**
    * <p>The service tier requested. May be a specific tier, default, or auto.</p>
    */
    @IncubatingApi
    const val OPENAI_REQUEST_SERVICE_TIER: String = "openai.request.service_tier"

    /**
    * <p>The service tier used for the response.</p>
    */
    @IncubatingApi
    const val OPENAI_RESPONSE_SERVICE_TIER: String = "openai.response.service_tier"

    /**
    * <p>A fingerprint to track any eventual change in the Generative AI environment.</p>
    */
    @IncubatingApi
    const val OPENAI_RESPONSE_SYSTEM_FINGERPRINT: String = "openai.response.system_fingerprint"

    /**
    * <p>OPENAI_API_TYPE</p>
    */
    @IncubatingApi
    enum class OpenaiApiTypeValues(val value: String) {

        /**
        * <p>The OpenAI <a href="https://developers.openai.com/api/reference/chat-completions/overview">Chat Completions API</a>.</p>
        */
        CHAT_COMPLETIONS("chat_completions"),

        /**
        * <p>The OpenAI <a href="https://developers.openai.com/api/reference/responses/overview">Responses API</a>.</p>
        */
        RESPONSES("responses"),
    }

    /**
    * <p>OPENAI_REQUEST_SERVICE_TIER</p>
    */
    @IncubatingApi
    enum class OpenaiRequestServiceTierValues(val value: String) {

        /**
        * <p>The system will utilize scale tier credits until they are exhausted.</p>
        */
        AUTO("auto"),

        /**
        * <p>The system will utilize the default scale tier.</p>
        */
        DEFAULT("default"),
    }
}
