package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'openshift'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object OpenshiftAttributes {
  

    /**
    * <p>The name of the cluster quota.</p>
    */
    @IncubatingApi
    const val OPENSHIFT_CLUSTERQUOTA_NAME: String = "openshift.clusterquota.name"

    /**
    * <p>The UID of the cluster quota.</p>
    */
    @IncubatingApi
    const val OPENSHIFT_CLUSTERQUOTA_UID: String = "openshift.clusterquota.uid"
}
