package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'oracle'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object OracleAttributes {
  

    /**
    * <p>The database domain associated with the connection.</p>
    * <p>Notes:</p>
    * <p>This attribute SHOULD be set to the value of the <c>DB_DOMAIN</c> initialization parameter,
    * as exposed in <c>v$parameter</c>. <c>DB_DOMAIN</c> defines the domain portion of the global
    * database name and SHOULD be configured when a database is, or may become, part of a
    * distributed environment. Its value consists of one or more valid identifiers
    * (alphanumeric ASCII characters) separated by periods.</p>
    */
    @IncubatingApi
    const val ORACLE_DB_DOMAIN: String = "oracle.db.domain"

    /**
    * <p>The instance name associated with the connection in an Oracle Real Application Clusters environment.</p>
    * <p>Notes:</p>
    * <p>There can be multiple instances associated with a single database service. It indicates the
    * unique instance name to which the connection is currently bound. For non-RAC databases, this value
    * defaults to the <c>oracle.db.name</c>.</p>
    */
    @IncubatingApi
    const val ORACLE_DB_INSTANCE_NAME: String = "oracle.db.instance.name"

    /**
    * <p>The database name associated with the connection.</p>
    * <p>Notes:</p>
    * <p>This attribute SHOULD be set to the value of the parameter <c>DB_NAME</c> exposed in <c>v$parameter</c>.</p>
    */
    @IncubatingApi
    const val ORACLE_DB_NAME: String = "oracle.db.name"

    /**
    * <p>The pluggable database (PDB) name associated with the connection.</p>
    * <p>Notes:</p>
    * <p>This attribute SHOULD reflect the PDB that the session is currently connected to.
    * If instrumentation cannot reliably obtain the active PDB name for each operation
    * without issuing an additional query (such as <c>SELECT SYS_CONTEXT</c>), it is
    * RECOMMENDED to fall back to the PDB name specified at connection establishment.</p>
    */
    @IncubatingApi
    const val ORACLE_DB_PDB: String = "oracle.db.pdb"

    /**
    * <p>The service name currently associated with the database connection.</p>
    * <p>Notes:</p>
    * <p>The effective service name for a connection can change during its lifetime,
    * for example after executing sql, <c>ALTER SESSION</c>. If an instrumentation cannot reliably
    * obtain the current service name for each operation without issuing an additional
    * query (such as <c>SELECT SYS_CONTEXT</c>), it is RECOMMENDED to fall back to the
    * service name originally provided at connection establishment.</p>
    */
    @IncubatingApi
    const val ORACLE_DB_SERVICE: String = "oracle.db.service"
}
