package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'oracle_cloud'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object OracleCloudAttributes {
  

    /**
    * <p>The OCI realm identifier that indicates the isolated partition in which the tenancy and its resources reside.</p>
    * <p>Notes:</p>
    * <p>See <a href="https://docs.oracle.com/iaas/Content/General/Concepts/regions.htm">OCI documentation on realms</a></p>
    */
    @IncubatingApi
    const val ORACLE_CLOUD_REALM: String = "oracle_cloud.realm"
}
