package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'os'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object OsAttributes {
  

    /**
    * <p>Unique identifier for a particular build or compilation of the operating system.</p>
    */
    @IncubatingApi
    const val OS_BUILD_ID: String = "os.build_id"

    /**
    * <p>Human readable (not intended to be parsed) OS version information, like e.g. reported by <c>ver</c> or <c>lsb_release -a</c> commands.</p>
    */
    @IncubatingApi
    const val OS_DESCRIPTION: String = "os.description"

    /**
    * <p>Human readable operating system name.</p>
    */
    @IncubatingApi
    const val OS_NAME: String = "os.name"

    /**
    * <p>The operating system type.</p>
    */
    @IncubatingApi
    const val OS_TYPE: String = "os.type"

    /**
    * <p>The version string of the operating system as defined in <a href="/docs/resource/README.md#version-attributes">Version Attributes</a>.</p>
    */
    @IncubatingApi
    const val OS_VERSION: String = "os.version"

    /**
    * <p>OS_TYPE</p>
    */
    @IncubatingApi
    enum class OsTypeValues(val value: String) {

        /**
        * <p>Microsoft Windows</p>
        */
        WINDOWS("windows"),

        /**
        * <p>Linux</p>
        */
        LINUX("linux"),

        /**
        * <p>Apple Darwin</p>
        */
        DARWIN("darwin"),

        /**
        * <p>FreeBSD</p>
        */
        FREEBSD("freebsd"),

        /**
        * <p>NetBSD</p>
        */
        NETBSD("netbsd"),

        /**
        * <p>OpenBSD</p>
        */
        OPENBSD("openbsd"),

        /**
        * <p>DragonFly BSD</p>
        */
        DRAGONFLYBSD("dragonflybsd"),

        /**
        * <p>HP-UX (Hewlett Packard Unix)</p>
        */
        HPUX("hpux"),

        /**
        * <p>AIX (Advanced Interactive eXecutive)</p>
        */
        AIX("aix"),

        /**
        * <p>SunOS, Oracle Solaris</p>
        */
        SOLARIS("solaris"),

        /**
        * <p>Deprecated. Use <c>zos</c> instead.</p>
        */
        Z_OS("z_os"),

        /**
        * <p>IBM z/OS</p>
        */
        ZOS("zos"),
    }
}
