package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'otel'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object OtelAttributes {

    /**
    * <p>Identifies the class / type of event.</p>
    * <p>Notes:</p>
    * <p>This attribute SHOULD be used by non-OTLP exporters when destination does not support <c>EventName</c> or equivalent field. This attribute MAY be used by applications using existing logging libraries so that it can be used to set the <c>EventName</c> field by Collector or SDK components.</p>
    */
    const val OTEL_EVENT_NAME: String = "otel.event.name"

    /**
    * <p>Deprecated. Use the <c>otel.scope.name</c> attribute</p>
    */
    @Deprecated("Replaced by `otel.scope.name`.")
    const val OTEL_LIBRARY_NAME: String = "otel.library.name"

    /**
    * <p>Deprecated. Use the <c>otel.scope.version</c> attribute.</p>
    */
    @Deprecated("Replaced by `otel.scope.version`.")
    const val OTEL_LIBRARY_VERSION: String = "otel.library.version"

    /**
    * <p>The name of the instrumentation scope - (<c>InstrumentationScope.Name</c> in OTLP).</p>
    */
    const val OTEL_SCOPE_NAME: String = "otel.scope.name"

    /**
    * <p>The version of the instrumentation scope - (<c>InstrumentationScope.Version</c> in OTLP).</p>
    */
    const val OTEL_SCOPE_VERSION: String = "otel.scope.version"

    /**
    * <p>Name of the code, either "OK" or "ERROR". MUST NOT be set if the status code is UNSET.</p>
    */
    const val OTEL_STATUS_CODE: String = "otel.status_code"

    /**
    * <p>Description of the Status if it has a value, otherwise not set.</p>
    */
    const val OTEL_STATUS_DESCRIPTION: String = "otel.status_description"

    /**
    * <p>OTEL_STATUS_CODE</p>
    */
    enum class OtelStatusCodeValues(val value: String) {

        /**
        * <p>The operation has been validated by an Application developer or Operator to have completed successfully.</p>
        */
        OK("OK"),

        /**
        * <p>The operation contains an error.</p>
        */
        ERROR("ERROR"),
    }
}
