package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'pprof'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object PprofAttributes {
  

    /**
    * <p>Provides an indication that multiple symbols map to this location's address, for example due to identical code folding by the linker. In that case the line information represents one of the multiple symbols. This field must be recomputed when the symbolization state of the profile changes.</p>
    */
    @IncubatingApi
    const val PPROF_LOCATION_IS_FOLDED: String = "pprof.location.is_folded"

    /**
    * <p>Indicates that there are filenames related to this mapping.</p>
    */
    @IncubatingApi
    const val PPROF_MAPPING_HAS_FILENAMES: String = "pprof.mapping.has_filenames"

    /**
    * <p>Indicates that there are functions related to this mapping.</p>
    */
    @IncubatingApi
    const val PPROF_MAPPING_HAS_FUNCTIONS: String = "pprof.mapping.has_functions"

    /**
    * <p>Indicates that there are inline frames related to this mapping.</p>
    */
    @IncubatingApi
    const val PPROF_MAPPING_HAS_INLINE_FRAMES: String = "pprof.mapping.has_inline_frames"

    /**
    * <p>Indicates that there are line numbers related to this mapping.</p>
    */
    @IncubatingApi
    const val PPROF_MAPPING_HAS_LINE_NUMBERS: String = "pprof.mapping.has_line_numbers"

    /**
    * <p>Free-form text associated with the profile. This field should not be used to store any machine-readable information, it is only for human-friendly content.</p>
    */
    @IncubatingApi
    const val PPROF_PROFILE_COMMENT: String = "pprof.profile.comment"

    /**
    * <p>Documentation link for this profile type.</p>
    * <p>Notes:</p>
    * <p>The URL must be absolute and may be missing if the profile was generated by code that did not supply a link</p>
    */
    @IncubatingApi
    const val PPROF_PROFILE_DOC_URL: String = "pprof.profile.doc_url"

    /**
    * <p>Frames with Function.function_name fully matching the regexp will be dropped from the samples, along with their successors.</p>
    */
    @IncubatingApi
    const val PPROF_PROFILE_DROP_FRAMES: String = "pprof.profile.drop_frames"

    /**
    * <p>Frames with Function.function_name fully matching the regexp will be kept, even if it matches drop_frames.</p>
    */
    @IncubatingApi
    const val PPROF_PROFILE_KEEP_FRAMES: String = "pprof.profile.keep_frames"

    /**
    * <p>Records the pprof's default_sample_type in the original profile. Not set if the default sample type was missing.</p>
    * <p>Notes:</p>
    * <p>This attribute, if present, MUST be set at the scope level (resource_profiles[].scope_profiles[].scope.attributes[]).</p>
    */
    @IncubatingApi
    const val PPROF_SCOPE_DEFAULT_SAMPLE_TYPE: String = "pprof.scope.default_sample_type"

    /**
    * <p>Records the indexes of the sample types in the original profile.</p>
    * <p>Notes:</p>
    * <p>This attribute, if present, MUST be set at the scope level (resource_profiles[].scope_profiles[].scope.attributes[]).</p>
    */
    @IncubatingApi
    const val PPROF_SCOPE_SAMPLE_TYPE_ORDER: String = "pprof.scope.sample_type_order"
}
