package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'process'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object ProcessAttributes {

    /**
    * <p>Deprecated, use <c>cpu.mode</c> instead.</p>
    */
    @Deprecated("Replaced by `cpu.mode`.")
    const val PROCESS_CPU_STATE: String = "process.cpu.state"

    /**
    * <p>"Deprecated, use <c>process.executable.build_id.htlhash</c> instead."</p>
    */
    @Deprecated("Replaced by `process.executable.build_id.htlhash`.")
    const val PROCESS_EXECUTABLE_BUILD_ID_PROFILING: String = "process.executable.build_id.profiling"

    /**
    * <p>Deprecated, use <c>system.paging.fault.type</c> instead.</p>
    */
    @Deprecated("Replaced by `system.paging.fault.type`.")
    const val PROCESS_PAGING_FAULT_TYPE: String = "process.paging.fault_type"

    /**
    * <p>PROCESS_CPU_STATE</p>
    */
    @Deprecated("Replaced by `cpu.mode`.")
    enum class ProcessCpuStateValues(val value: String) {

        /**
        * <p>system.</p>
        */
        SYSTEM("system"),

        /**
        * <p>user.</p>
        */
        USER("user"),

        /**
        * <p>wait.</p>
        */
        WAIT("wait"),
    }

    /**
    * <p>PROCESS_PAGING_FAULT_TYPE</p>
    */
    @Deprecated("Replaced by `system.paging.fault.type`.")
    enum class ProcessPagingFaultTypeValues(val value: String) {

        /**
        * <p>major.</p>
        */
        MAJOR("major"),

        /**
        * <p>minor.</p>
        */
        MINOR("minor"),
    }

}
