package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'rpc'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object RpcAttributes {
  

    /**
    * <p>Deprecated, use <c>rpc.response.status_code</c> attribute instead.</p>
    */
    @Deprecated("Replaced by `rpc.response.status_code`.")
    const val RPC_CONNECT_RPC_ERROR_CODE: String = "rpc.connect_rpc.error_code"

    /**
    * <p>Deprecated, use <c>rpc.request.metadata</c> instead.</p>
    */
    @Deprecated("Replaced by `rpc.request.metadata`.")
    const val RPC_CONNECT_RPC_REQUEST_METADATA: String = "rpc.connect_rpc.request.metadata"

    /**
    * <p>Deprecated, use <c>rpc.response.metadata</c> instead.</p>
    */
    @Deprecated("Replaced by `rpc.response.metadata`.")
    const val RPC_CONNECT_RPC_RESPONSE_METADATA: String = "rpc.connect_rpc.response.metadata"

    /**
    * <p>Deprecated, use <c>rpc.request.metadata</c> instead.</p>
    */
    @Deprecated("Replaced by `rpc.request.metadata`.")
    const val RPC_GRPC_REQUEST_METADATA: String = "rpc.grpc.request.metadata"

    /**
    * <p>Deprecated, use <c>rpc.response.metadata</c> instead.</p>
    */
    @Deprecated("Replaced by `rpc.response.metadata`.")
    const val RPC_GRPC_RESPONSE_METADATA: String = "rpc.grpc.response.metadata"

    /**
    * <p>Deprecated, use string representation on the <c>rpc.response.status_code</c> attribute instead.</p>
    */
    @Deprecated("Use string representation of the gRPC status code on the `rpc.response.status_code` attribute.")
    const val RPC_GRPC_STATUS_CODE: String = "rpc.grpc.status_code"

    /**
    * <p>Deprecated, use string representation on the <c>rpc.response.status_code</c> attribute instead.</p>
    */
    @Deprecated("Use string representation of the error code on the `rpc.response.status_code` attribute.")
    const val RPC_JSONRPC_ERROR_CODE: String = "rpc.jsonrpc.error_code"

    /**
    * <p>Deprecated, use span status description or <c>error.message</c> attribute on other signals.</p>
    */
    @Deprecated("Use the span status description or `error.message` attribute on other signals.")
    const val RPC_JSONRPC_ERROR_MESSAGE: String = "rpc.jsonrpc.error_message"

    /**
    * <p>Deprecated, use <c>jsonrpc.request.id</c> instead.</p>
    */
    @Deprecated("Replaced by `jsonrpc.request.id`.")
    const val RPC_JSONRPC_REQUEST_ID: String = "rpc.jsonrpc.request_id"

    /**
    * <p>Deprecated, use <c>jsonrpc.protocol.version</c> instead.</p>
    */
    @Deprecated("Replaced by `jsonrpc.protocol.version`.")
    const val RPC_JSONRPC_VERSION: String = "rpc.jsonrpc.version"

    /**
    * <p>Compressed size of the message in bytes.</p>
    */
    @IncubatingApi
    const val RPC_MESSAGE_COMPRESSED_SIZE: String = "rpc.message.compressed_size"

    /**
    * <p>MUST be calculated as two different counters starting from <c>1</c> one for sent messages and one for received message.</p>
    * <p>Notes:</p>
    * <p>This way we guarantee that the values will be consistent between different implementations.</p>
    */
    @IncubatingApi
    const val RPC_MESSAGE_ID: String = "rpc.message.id"

    /**
    * <p>Whether this is a received or sent message.</p>
    */
    @IncubatingApi
    const val RPC_MESSAGE_TYPE: String = "rpc.message.type"

    /**
    * <p>Uncompressed size of the message in bytes.</p>
    */
    @IncubatingApi
    const val RPC_MESSAGE_UNCOMPRESSED_SIZE: String = "rpc.message.uncompressed_size"

    /**
    * <p>The fully-qualified logical name of the method from the RPC interface perspective.</p>
    * <p>Notes:</p>
    * <p>The method name MAY have unbounded cardinality in edge or error cases.</p>
    * <p>Some RPC frameworks or libraries provide a fixed set of recognized methods
    * for client stubs and server implementations. Instrumentations for such
    * frameworks MUST set this attribute to the original method name only
    * when the method is recognized by the framework or library.</p>
    * <p>When the method is not recognized, for example, when the server receives
    * a request for a method that is not predefined on the server, or when
    * instrumentation is not able to reliably detect if the method is predefined,
    * the attribute MUST be set to <c>_OTHER</c>. In such cases, tracing
    * instrumentations MUST also set <c>rpc.method_original</c> attribute to
    * the original method value.</p>
    * <p>If the RPC instrumentation could end up converting valid RPC methods to
    * <c>_OTHER</c>, then it SHOULD provide a way to configure the list of recognized
    * RPC methods.</p>
    * <p>The <c>rpc.method</c> can be different from the name of any implementing
    * method/function.
    * The <c>code.function.name</c> attribute may be used to record the fully-qualified
    * method actually executing the call on the server side, or the
    * RPC client stub method on the client side.</p>
    */
    @IncubatingApi
    const val RPC_METHOD: String = "rpc.method"

    /**
    * <p>The original name of the method used by the client.</p>
    */
    @IncubatingApi
    const val RPC_METHOD_ORIGINAL: String = "rpc.method_original"

    /**
    * <p>RPC request metadata, <c><key></c> being the normalized RPC metadata key (lowercase), the value being the metadata values.</p>
    * <p>Notes:</p>
    * <p>Instrumentations SHOULD require an explicit configuration of which metadata values are to be captured.
    * Including all request metadata values can be a security risk - explicit configuration helps avoid leaking sensitive information.</p>
    * <p>For example, a property <c>my-custom-key</c> with value <c>["1.2.3.4", "1.2.3.5"]</c> SHOULD be recorded as
    * <c>rpc.request.metadata.my-custom-key</c> attribute with value <c>["1.2.3.4", "1.2.3.5"]</c></p>
    */
    @IncubatingApi
    const val RPC_REQUEST_METADATA: String = "rpc.request.metadata"

    /**
    * <p>RPC response metadata, <c><key></c> being the normalized RPC metadata key (lowercase), the value being the metadata values.</p>
    * <p>Notes:</p>
    * <p>Instrumentations SHOULD require an explicit configuration of which metadata values are to be captured.
    * Including all response metadata values can be a security risk - explicit configuration helps avoid leaking sensitive information.</p>
    * <p>For example, a property <c>my-custom-key</c> with value <c>["attribute_value"]</c> SHOULD be recorded as
    * the <c>rpc.response.metadata.my-custom-key</c> attribute with value <c>["attribute_value"]</c></p>
    */
    @IncubatingApi
    const val RPC_RESPONSE_METADATA: String = "rpc.response.metadata"

    /**
    * <p>Status code of the RPC returned by the RPC server or generated by the client</p>
    * <p>Notes:</p>
    * <p>Usually it represents an error code, but may also represent partial success, warning, or differentiate between various types of successful outcomes.
    * Semantic conventions for individual RPC frameworks SHOULD document what <c>rpc.response.status_code</c> means in the context of that system and which values are considered to represent errors.</p>
    */
    @IncubatingApi
    const val RPC_RESPONSE_STATUS_CODE: String = "rpc.response.status_code"

    /**
    * <p>Deprecated, use fully-qualified <c>rpc.method</c> instead.</p>
    */
    @Deprecated("Value should be included in `rpc.method` which is expected to be a fully-qualified name.")
    const val RPC_SERVICE: String = "rpc.service"

    /**
    * <p>Deprecated, use <c>rpc.system.name</c> attribute instead.</p>
    */
    @Deprecated("Replaced by `rpc.system.name`.")
    const val RPC_SYSTEM: String = "rpc.system"

    /**
    * <p>The Remote Procedure Call (RPC) system.</p>
    * <p>Notes:</p>
    * <p>The client and server RPC systems may differ for the same RPC interaction. For example, a client may use Apache Dubbo or Connect RPC to communicate with a server that uses gRPC since both protocols provide compatibility with gRPC.</p>
    */
    @IncubatingApi
    const val RPC_SYSTEM_NAME: String = "rpc.system.name"

    /**
    * <p>RPC_CONNECT_RPC_ERROR_CODE</p>
    */
    @Deprecated("Replaced by `rpc.response.status_code`.")
    enum class RpcConnectRpcErrorCodeValues(val value: String) {

        /**
        * <p>cancelled.</p>
        */
        CANCELLED("cancelled"),

        /**
        * <p>unknown.</p>
        */
        UNKNOWN("unknown"),

        /**
        * <p>invalid_argument.</p>
        */
        INVALID_ARGUMENT("invalid_argument"),

        /**
        * <p>deadline_exceeded.</p>
        */
        DEADLINE_EXCEEDED("deadline_exceeded"),

        /**
        * <p>not_found.</p>
        */
        NOT_FOUND("not_found"),

        /**
        * <p>already_exists.</p>
        */
        ALREADY_EXISTS("already_exists"),

        /**
        * <p>permission_denied.</p>
        */
        PERMISSION_DENIED("permission_denied"),

        /**
        * <p>resource_exhausted.</p>
        */
        RESOURCE_EXHAUSTED("resource_exhausted"),

        /**
        * <p>failed_precondition.</p>
        */
        FAILED_PRECONDITION("failed_precondition"),

        /**
        * <p>aborted.</p>
        */
        ABORTED("aborted"),

        /**
        * <p>out_of_range.</p>
        */
        OUT_OF_RANGE("out_of_range"),

        /**
        * <p>unimplemented.</p>
        */
        UNIMPLEMENTED("unimplemented"),

        /**
        * <p>internal.</p>
        */
        INTERNAL("internal"),

        /**
        * <p>unavailable.</p>
        */
        UNAVAILABLE("unavailable"),

        /**
        * <p>data_loss.</p>
        */
        DATA_LOSS("data_loss"),

        /**
        * <p>unauthenticated.</p>
        */
        UNAUTHENTICATED("unauthenticated"),
    }

    /**
    * <p>RPC_GRPC_STATUS_CODE</p>
    */
    @Deprecated("Use string representation of the gRPC status code on the `rpc.response.status_code` attribute.")
    enum class RpcGrpcStatusCodeValues(val value: Int) {

        /**
        * <p>OK</p>
        */
        OK(0),

        /**
        * <p>CANCELLED</p>
        */
        CANCELLED(1),

        /**
        * <p>UNKNOWN</p>
        */
        UNKNOWN(2),

        /**
        * <p>INVALID_ARGUMENT</p>
        */
        INVALID_ARGUMENT(3),

        /**
        * <p>DEADLINE_EXCEEDED</p>
        */
        DEADLINE_EXCEEDED(4),

        /**
        * <p>NOT_FOUND</p>
        */
        NOT_FOUND(5),

        /**
        * <p>ALREADY_EXISTS</p>
        */
        ALREADY_EXISTS(6),

        /**
        * <p>PERMISSION_DENIED</p>
        */
        PERMISSION_DENIED(7),

        /**
        * <p>RESOURCE_EXHAUSTED</p>
        */
        RESOURCE_EXHAUSTED(8),

        /**
        * <p>FAILED_PRECONDITION</p>
        */
        FAILED_PRECONDITION(9),

        /**
        * <p>ABORTED</p>
        */
        ABORTED(10),

        /**
        * <p>OUT_OF_RANGE</p>
        */
        OUT_OF_RANGE(11),

        /**
        * <p>UNIMPLEMENTED</p>
        */
        UNIMPLEMENTED(12),

        /**
        * <p>INTERNAL</p>
        */
        INTERNAL(13),

        /**
        * <p>UNAVAILABLE</p>
        */
        UNAVAILABLE(14),

        /**
        * <p>DATA_LOSS</p>
        */
        DATA_LOSS(15),

        /**
        * <p>UNAUTHENTICATED</p>
        */
        UNAUTHENTICATED(16),
    }

    /**
    * <p>RPC_MESSAGE_TYPE</p>
    */
    @IncubatingApi
    enum class RpcMessageTypeValues(val value: String) {

        /**
        * <p>sent.</p>
        */
        SENT("SENT"),

        /**
        * <p>received.</p>
        */
        RECEIVED("RECEIVED"),
    }

    /**
    * <p>RPC_SYSTEM</p>
    */
    @Deprecated("Replaced by `rpc.system.name`.")
    enum class RpcSystemValues(val value: String) {

        /**
        * <p>gRPC</p>
        */
        GRPC("grpc"),

        /**
        * <p>Java RMI</p>
        */
        JAVA_RMI("java_rmi"),

        /**
        * <p>.NET WCF</p>
        */
        DOTNET_WCF("dotnet_wcf"),

        /**
        * <p>Apache Dubbo</p>
        */
        APACHE_DUBBO("apache_dubbo"),

        /**
        * <p>Connect RPC</p>
        */
        CONNECT_RPC("connect_rpc"),

        /**
        * <p><a href="https://datatracker.ietf.org/doc/html/rfc5531">ONC RPC (Sun RPC)</a></p>
        */
        ONC_RPC("onc_rpc"),

        /**
        * <p>JSON-RPC</p>
        */
        JSONRPC("jsonrpc"),
    }

    /**
    * <p>RPC_SYSTEM_NAME</p>
    */
    @IncubatingApi
    enum class RpcSystemNameValues(val value: String) {

        /**
        * <p><a href="https://grpc.io/">gRPC</a></p>
        */
        GRPC("grpc"),

        /**
        * <p><a href="https://dubbo.apache.org/">Apache Dubbo</a></p>
        */
        DUBBO("dubbo"),

        /**
        * <p><a href="https://connectrpc.com/">Connect RPC</a></p>
        */
        CONNECTRPC("connectrpc"),

        /**
        * <p><a href="https://www.jsonrpc.org/">JSON-RPC</a></p>
        */
        JSONRPC("jsonrpc"),
    }
}
