package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'server'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object ServerAttributes {
  

    /**
    * <p>Server domain name if available without reverse DNS lookup; otherwise, IP address or Unix domain socket name.</p>
    * <p>Notes:</p>
    * <p>When observed from the client side, and when communicating through an intermediary, <c>server.address</c> SHOULD represent the server address behind any intermediaries, for example proxies, if it's available.</p>
    */
    const val SERVER_ADDRESS: String = "server.address"

    /**
    * <p>Server port number.</p>
    * <p>Notes:</p>
    * <p>When observed from the client side, and when communicating through an intermediary, <c>server.port</c> SHOULD represent the server port behind any intermediaries, for example proxies, if it's available.</p>
    */
    const val SERVER_PORT: String = "server.port"
}
