package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'system'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object SystemAttributes {
  

    /**
    * <p>Deprecated, use <c>cpu.logical_number</c> instead.</p>
    */
    @Deprecated("Replaced by `cpu.logical_number`.")
    const val SYSTEM_CPU_LOGICAL_NUMBER: String = "system.cpu.logical_number"

    /**
    * <p>Deprecated, use <c>cpu.mode</c> instead.</p>
    */
    @Deprecated("Replaced by `cpu.mode`.")
    const val SYSTEM_CPU_STATE: String = "system.cpu.state"

    /**
    * <p>The device identifier</p>
    */
    @IncubatingApi
    const val SYSTEM_DEVICE: String = "system.device"

    /**
    * <p>The filesystem mode</p>
    */
    @IncubatingApi
    const val SYSTEM_FILESYSTEM_MODE: String = "system.filesystem.mode"

    /**
    * <p>The filesystem mount path</p>
    */
    @IncubatingApi
    const val SYSTEM_FILESYSTEM_MOUNTPOINT: String = "system.filesystem.mountpoint"

    /**
    * <p>The filesystem state</p>
    */
    @IncubatingApi
    const val SYSTEM_FILESYSTEM_STATE: String = "system.filesystem.state"

    /**
    * <p>The filesystem type</p>
    */
    @IncubatingApi
    const val SYSTEM_FILESYSTEM_TYPE: String = "system.filesystem.type"

    /**
    * <p>The Linux Slab memory state</p>
    */
    @IncubatingApi
    const val SYSTEM_MEMORY_LINUX_SLAB_STATE: String = "system.memory.linux.slab.state"

    /**
    * <p>The memory state</p>
    */
    @IncubatingApi
    const val SYSTEM_MEMORY_STATE: String = "system.memory.state"

    /**
    * <p>Deprecated, use <c>network.connection.state</c> instead.</p>
    */
    @Deprecated("Replaced by `network.connection.state`.")
    const val SYSTEM_NETWORK_STATE: String = "system.network.state"

    /**
    * <p>The paging access direction</p>
    */
    @IncubatingApi
    const val SYSTEM_PAGING_DIRECTION: String = "system.paging.direction"

    /**
    * <p>The paging fault type</p>
    */
    @IncubatingApi
    const val SYSTEM_PAGING_FAULT_TYPE: String = "system.paging.fault.type"

    /**
    * <p>The memory paging state</p>
    */
    @IncubatingApi
    const val SYSTEM_PAGING_STATE: String = "system.paging.state"

    /**
    * <p>Deprecated, use <c>system.paging.fault.type</c> instead.</p>
    */
    @Deprecated("Replaced by `system.paging.fault.type`.")
    const val SYSTEM_PAGING_TYPE: String = "system.paging.type"

    /**
    * <p>Deprecated, use <c>process.state</c> instead.</p>
    */
    @Deprecated("Replaced by `process.state`.")
    const val SYSTEM_PROCESS_STATUS: String = "system.process.status"

    /**
    * <p>Deprecated, use <c>process.state</c> instead.</p>
    */
    @Deprecated("Replaced by `process.state`.")
    const val SYSTEM_PROCESSES_STATUS: String = "system.processes.status"

    /**
    * <p>SYSTEM_CPU_STATE</p>
    */
    @Deprecated("Replaced by `cpu.mode`.")
    enum class SystemCpuStateValues(val value: String) {

        /**
        * <p>user.</p>
        */
        USER("user"),

        /**
        * <p>system.</p>
        */
        SYSTEM("system"),

        /**
        * <p>nice.</p>
        */
        NICE("nice"),

        /**
        * <p>idle.</p>
        */
        IDLE("idle"),

        /**
        * <p>iowait.</p>
        */
        IOWAIT("iowait"),

        /**
        * <p>interrupt.</p>
        */
        INTERRUPT("interrupt"),

        /**
        * <p>steal.</p>
        */
        STEAL("steal"),
    }

    /**
    * <p>SYSTEM_FILESYSTEM_STATE</p>
    */
    @IncubatingApi
    enum class SystemFilesystemStateValues(val value: String) {

        /**
        * <p>used.</p>
        */
        USED("used"),

        /**
        * <p>free.</p>
        */
        FREE("free"),

        /**
        * <p>reserved.</p>
        */
        RESERVED("reserved"),
    }

    /**
    * <p>SYSTEM_FILESYSTEM_TYPE</p>
    */
    @IncubatingApi
    enum class SystemFilesystemTypeValues(val value: String) {

        /**
        * <p>fat32.</p>
        */
        FAT32("fat32"),

        /**
        * <p>exfat.</p>
        */
        EXFAT("exfat"),

        /**
        * <p>ntfs.</p>
        */
        NTFS("ntfs"),

        /**
        * <p>refs.</p>
        */
        REFS("refs"),

        /**
        * <p>hfsplus.</p>
        */
        HFSPLUS("hfsplus"),

        /**
        * <p>ext4.</p>
        */
        EXT4("ext4"),
    }

    /**
    * <p>SYSTEM_MEMORY_LINUX_SLAB_STATE</p>
    */
    @IncubatingApi
    enum class SystemMemoryLinuxSlabStateValues(val value: String) {

        /**
        * <p>reclaimable.</p>
        */
        RECLAIMABLE("reclaimable"),

        /**
        * <p>unreclaimable.</p>
        */
        UNRECLAIMABLE("unreclaimable"),
    }

    /**
    * <p>SYSTEM_MEMORY_STATE</p>
    */
    @IncubatingApi
    enum class SystemMemoryStateValues(val value: String) {

        /**
        * <p>Actual used virtual memory in bytes.</p>
        */
        USED("used"),

        /**
        * <p>free.</p>
        */
        FREE("free"),

        /**
        * <p>shared.</p>
        */
        SHARED("shared"),

        /**
        * <p>buffers.</p>
        */
        BUFFERS("buffers"),

        /**
        * <p>cached.</p>
        */
        CACHED("cached"),
    }

    /**
    * <p>SYSTEM_NETWORK_STATE</p>
    */
    @Deprecated("Replaced by `network.connection.state`.")
    enum class SystemNetworkStateValues(val value: String) {

        /**
        * <p>close.</p>
        */
        CLOSE("close"),

        /**
        * <p>close_wait.</p>
        */
        CLOSE_WAIT("close_wait"),

        /**
        * <p>closing.</p>
        */
        CLOSING("closing"),

        /**
        * <p>delete.</p>
        */
        DELETE("delete"),

        /**
        * <p>established.</p>
        */
        ESTABLISHED("established"),

        /**
        * <p>fin_wait_1.</p>
        */
        FIN_WAIT_1("fin_wait_1"),

        /**
        * <p>fin_wait_2.</p>
        */
        FIN_WAIT_2("fin_wait_2"),

        /**
        * <p>last_ack.</p>
        */
        LAST_ACK("last_ack"),

        /**
        * <p>listen.</p>
        */
        LISTEN("listen"),

        /**
        * <p>syn_recv.</p>
        */
        SYN_RECV("syn_recv"),

        /**
        * <p>syn_sent.</p>
        */
        SYN_SENT("syn_sent"),

        /**
        * <p>time_wait.</p>
        */
        TIME_WAIT("time_wait"),
    }

    /**
    * <p>SYSTEM_PAGING_DIRECTION</p>
    */
    @IncubatingApi
    enum class SystemPagingDirectionValues(val value: String) {

        /**
        * <p>in.</p>
        */
        IN("in"),

        /**
        * <p>out.</p>
        */
        OUT("out"),
    }

    /**
    * <p>SYSTEM_PAGING_FAULT_TYPE</p>
    */
    @IncubatingApi
    enum class SystemPagingFaultTypeValues(val value: String) {

        /**
        * <p>major.</p>
        */
        MAJOR("major"),

        /**
        * <p>minor.</p>
        */
        MINOR("minor"),
    }

    /**
    * <p>SYSTEM_PAGING_STATE</p>
    */
    @IncubatingApi
    enum class SystemPagingStateValues(val value: String) {

        /**
        * <p>used.</p>
        */
        USED("used"),

        /**
        * <p>free.</p>
        */
        FREE("free"),
    }

    /**
    * <p>SYSTEM_PAGING_TYPE</p>
    */
    @Deprecated("Replaced by `system.paging.fault.type`.")
    enum class SystemPagingTypeValues(val value: String) {

        /**
        * <p>major.</p>
        */
        MAJOR("major"),

        /**
        * <p>minor.</p>
        */
        MINOR("minor"),
    }

    /**
    * <p>SYSTEM_PROCESS_STATUS</p>
    */
    @Deprecated("Replaced by `process.state`.")
    enum class SystemProcessStatusValues(val value: String) {

        /**
        * <p>running.</p>
        */
        RUNNING("running"),

        /**
        * <p>sleeping.</p>
        */
        SLEEPING("sleeping"),

        /**
        * <p>stopped.</p>
        */
        STOPPED("stopped"),

        /**
        * <p>defunct.</p>
        */
        DEFUNCT("defunct"),
    }

    /**
    * <p>SYSTEM_PROCESSES_STATUS</p>
    */
    @Deprecated("Replaced by `process.state`.")
    enum class SystemProcessesStatusValues(val value: String) {

        /**
        * <p>running.</p>
        */
        RUNNING("running"),

        /**
        * <p>sleeping.</p>
        */
        SLEEPING("sleeping"),

        /**
        * <p>stopped.</p>
        */
        STOPPED("stopped"),

        /**
        * <p>defunct.</p>
        */
        DEFUNCT("defunct"),
    }
}
