package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'thread'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object ThreadAttributes {
  

    /**
    * <p>Current "managed" thread ID (as opposed to OS thread ID).</p>
    */
    @IncubatingApi
    const val THREAD_ID: String = "thread.id"

    /**
    * <p>Current thread name.</p>
    */
    @IncubatingApi
    const val THREAD_NAME: String = "thread.name"
}
