package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'thread'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object ThreadAttributes {
  

    /**
    * <p>Current "managed" thread ID (as opposed to OS thread ID).</p>
    * <p>Notes:</p>
    * <p>Examples of where the value can be extracted from:</p>
    * <p>| Language or platform | Source |
    * | --- | --- |
    * | JVM | <c>Thread.currentThread().threadId()</c> |
    * | .NET | <c>Thread.CurrentThread.ManagedThreadId</c> |
    * | Python | <c>threading.current_thread().ident</c> |
    * | Ruby | <c>Thread.current.object_id</c> |
    * | C++ | <c>std::this_thread::get_id()</c> |
    * | Erlang | <c>erlang:self()</c> |</p>
    */
    @IncubatingApi
    const val THREAD_ID: String = "thread.id"

    /**
    * <p>Current thread name.</p>
    * <p>Notes:</p>
    * <p>Examples of where the value can be extracted from:</p>
    * <p>| Language or platform | Source |
    * | --- | --- |
    * | JVM | <c>Thread.currentThread().getName()</c> |
    * | .NET | <c>Thread.CurrentThread.Name</c> |
    * | Python | <c>threading.current_thread().name</c> |
    * | Ruby | <c>Thread.current.name</c> |
    * | Erlang | <c>erlang:process_info(self(), registered_name)</c> |</p>
    */
    @IncubatingApi
    const val THREAD_NAME: String = "thread.name"
}
