package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'tls'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object TlsAttributes {

    /**
    * <p>Deprecated, use <c>server.address</c> instead.</p>
    */
    @Deprecated("Replaced by `server.address`.")
    const val TLS_CLIENT_SERVER_NAME: String = "tls.client.server_name"

}
