package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'url'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object UrlAttributes {

    /**
    * <p>The <a href="https://www.rfc-editor.org/rfc/rfc3986#section-3.5">URI fragment</a> component</p>
    */
    const val URL_FRAGMENT: String = "url.fragment"

    /**
    * <p>Absolute URL describing a network resource according to <a href="https://www.rfc-editor.org/rfc/rfc3986">RFC3986</a></p>
    * <p>Notes:</p>
    * <p>For network calls, URL usually has <c>scheme://host[:port][path][?query][#fragment]</c> format, where the fragment
    * is not transmitted over HTTP, but if it is known, it SHOULD be included nevertheless.</p>
    * <p><c>url.full</c> MUST NOT contain credentials passed via URL in form of <c>https://username:password@www.example.com/</c>.
    * In such case username and password SHOULD be redacted and attribute's value SHOULD be <c>https://REDACTED:REDACTED@www.example.com/</c>.</p>
    * <p><c>url.full</c> SHOULD capture the absolute URL when it is available (or can be reconstructed).</p>
    * <p>Sensitive content provided in <c>url.full</c> SHOULD be scrubbed when instrumentations can identify it.</p>
    * <p>
    * Query string values for the following keys SHOULD be redacted by default and replaced by the
    * value <c>REDACTED</c>:</p>
    * <ul>
    *   <li><a href="https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html#RESTAuthenticationQueryStringAuth"><c>AWSAccessKeyId</c></a></li>
    *   <li><a href="https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html#RESTAuthenticationQueryStringAuth"><c>Signature</c></a></li>
    *   <li><a href="https://learn.microsoft.com/azure/storage/common/storage-sas-overview#sas-token"><c>sig</c></a></li>
    *   <li><a href="https://cloud.google.com/storage/docs/access-control/signed-urls"><c>X-Goog-Signature</c></a></li>
    * </ul>
    * <p>This list is subject to change over time.</p>
    * <p>Matching of query parameter keys against the sensitive list SHOULD be case-sensitive.</p>
    * <p>
    * Instrumentation MAY provide a way to override this list via declarative configuration.
    * If so, it SHOULD use the <c>sensitive_query_parameters</c> property
    * (an array of case-sensitive strings with minimum items 0) under
    * <c>.instrumentation/development.general.sanitization.url</c>.
    * This list is a full override of the default sensitive query parameter keys,
    * it is not a list of keys in addition to the defaults.</p>
    * <p>When a query string value is redacted, the query string key SHOULD still be preserved, e.g.
    * <c>https://www.example.com/path?color=blue&sig=REDACTED</c>.</p>
    */
    const val URL_FULL: String = "url.full"

    /**
    * <p>The <a href="https://www.rfc-editor.org/rfc/rfc3986#section-3.3">URI path</a> component</p>
    * <p>Notes:</p>
    * <p>Sensitive content provided in <c>url.path</c> SHOULD be scrubbed when instrumentations can identify it.</p>
    */
    const val URL_PATH: String = "url.path"

    /**
    * <p>The <a href="https://www.rfc-editor.org/rfc/rfc3986#section-3.4">URI query</a> component</p>
    * <p>Notes:</p>
    * <p>Sensitive content provided in <c>url.query</c> SHOULD be scrubbed when instrumentations can identify it.</p>
    * <p>
    * Query string values for the following keys SHOULD be redacted by default and replaced by the value <c>REDACTED</c>:</p>
    * <ul>
    *   <li><a href="https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html#RESTAuthenticationQueryStringAuth"><c>AWSAccessKeyId</c></a></li>
    *   <li><a href="https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html#RESTAuthenticationQueryStringAuth"><c>Signature</c></a></li>
    *   <li><a href="https://learn.microsoft.com/azure/storage/common/storage-sas-overview#sas-token"><c>sig</c></a></li>
    *   <li><a href="https://cloud.google.com/storage/docs/access-control/signed-urls"><c>X-Goog-Signature</c></a></li>
    * </ul>
    * <p>This list is subject to change over time.</p>
    * <p>Matching of query parameter keys against the sensitive list SHOULD be case-sensitive.</p>
    * <p>Instrumentation MAY provide a way to override this list via declarative configuration.
    * If so, it SHOULD use the <c>sensitive_query_parameters</c> property
    * (an array of case-sensitive strings with minimum items 0) under
    * <c>.instrumentation/development.general.sanitization.url</c>.
    * This list is a full override of the default sensitive query parameter keys,
    * it is not a list of keys in addition to the defaults.</p>
    * <p>When a query string value is redacted, the query string key SHOULD still be preserved, e.g.
    * <c>q=OpenTelemetry&sig=REDACTED</c>.</p>
    */
    const val URL_QUERY: String = "url.query"

    /**
    * <p>The <a href="https://www.rfc-editor.org/rfc/rfc3986#section-3.1">URI scheme</a> component identifying the used protocol.</p>
    */
    const val URL_SCHEME: String = "url.scheme"

}
