package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'vcs'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object VcsAttributes {

    /**
    * <p>Deprecated, use <c>vcs.change.id</c> instead.</p>
    */
    @Deprecated("Replaced by `vcs.change.id`.")
    const val VCS_REPOSITORY_CHANGE_ID: String = "vcs.repository.change.id"

    /**
    * <p>Deprecated, use <c>vcs.change.title</c> instead.</p>
    */
    @Deprecated("Replaced by `vcs.change.title`.")
    const val VCS_REPOSITORY_CHANGE_TITLE: String = "vcs.repository.change.title"

    /**
    * <p>Deprecated, use <c>vcs.ref.head.name</c> instead.</p>
    */
    @Deprecated("Replaced by `vcs.ref.head.name`.")
    const val VCS_REPOSITORY_REF_NAME: String = "vcs.repository.ref.name"

    /**
    * <p>Deprecated, use <c>vcs.ref.head.revision</c> instead.</p>
    */
    @Deprecated("Replaced by `vcs.ref.head.revision`.")
    const val VCS_REPOSITORY_REF_REVISION: String = "vcs.repository.ref.revision"

    /**
    * <p>Deprecated, use <c>vcs.ref.head.type</c> instead.</p>
    */
    @Deprecated("Replaced by `vcs.ref.head.type`.")
    const val VCS_REPOSITORY_REF_TYPE: String = "vcs.repository.ref.type"

    /**
    * <p>VCS_REPOSITORY_REF_TYPE</p>
    */
    @Deprecated("Replaced by `vcs.ref.head.type`.")
    enum class VcsRepositoryRefTypeValues(val value: String) {

        /**
        * <p><a href="https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefbranchabranch">branch</a></p>
        */
        BRANCH("branch"),

        /**
        * <p><a href="https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddeftagatag">tag</a></p>
        */
        TAG("tag"),
    }

}
