package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'webengine'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object WebengineAttributes {
  

    /**
    * <p>Additional description of the web engine (e.g. detailed version and edition information).</p>
    */
    @IncubatingApi
    const val WEBENGINE_DESCRIPTION: String = "webengine.description"

    /**
    * <p>The name of the web engine.</p>
    */
    @IncubatingApi
    const val WEBENGINE_NAME: String = "webengine.name"

    /**
    * <p>The version of the web engine.</p>
    */
    @IncubatingApi
    const val WEBENGINE_VERSION: String = "webengine.version"
}
