package io.opentelemetry.kotlin.semconv

/**
 * Autogenerated OpenTelemetry semantic conventions for 'zos'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object ZosAttributes {
  

    /**
    * <p>The System Management Facility (SMF) Identifier uniquely identified a z/OS system within a SYSPLEX or mainframe environment and is used for system and performance analysis.</p>
    */
    @IncubatingApi
    const val ZOS_SMF_ID: String = "zos.smf.id"

    /**
    * <p>The name of the SYSPLEX to which the z/OS system belongs too.</p>
    */
    @IncubatingApi
    const val ZOS_SYSPLEX_NAME: String = "zos.sysplex.name"
}
