package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'app.crash'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>This event represents a termination of a user-facing application due to
* unrecoverable programming errors such as exceptions or signals that
* indicate an error has happened at a lower level.</p>
* <p>Notes:</p>
* <p>Crash events can be produced asynchronously by an OTel SDK instance that is
* not running in the application instance in which the crash happened. For
* example, the instrumentation may report crashes from previous app instances
* based on information found in tombstones on disk.
* If the reporter of the crash is not the crashing application instance itself,
* relevant resource attributes that identify the application instance that
* crashed MUST be provided as event attributes so that the corresponding
* attributes from the reporter's resource aren't used instead.
* How the instrumentation will determine whether an instance of a crash has
* already been reported and how the necessary data will be retrieved is left up
* to the instrumentation. Providing enough data to dedupe is NOT REQUIRED.</p>
*/
@ExperimentalApi
@IncubatingApi
class AppCrashEvent(
    /**
    * <p>Unique identifier for a particular build or compilation of the application.</p>
    */
    val appBuildId: String? = null,
    /**
    * <p>A unique identifier representing an instance of an end-user facing app crash.</p>
    * <p>Notes:</p>
    * <p>Its value MAY be meaningful and be used as a reference for telemetry and metadata recorded by
    * the same instrumentation (e.g. it is an ID generated by an external source that captured the crash).
    * It MAY come from a source external to the instrumentation such that it can be used to look up additional
    * data from other sources as well as facilitate deduplication.</p>
    */
    val appCrashId: String? = null,
    /**
    * <p>The exception message.</p>
    * <p>Notes:</p>
    * <p>If this contains obfuscated symbols, <c>app.build_id</c> SHOULD be provided so they can be deobfuscated.</p>
    */
    val exceptionMessage: String? = null,
    /**
    * <p>A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG.</p>
    * <p>Notes:</p>
    * <p>If this contains obfuscated symbols, <c>app.build_id</c> SHOULD be provided so they can be deobfuscated.</p>
    */
    val exceptionStacktrace: String? = null,
    /**
    * <p>The type of the exception (its fully-qualified class name, if applicable). The dynamic type of the exception should be preferred over the static type in languages that support it.</p>
    * <p>Notes:</p>
    * <p>If this contains obfuscated symbols, <c>app.build_id</c> SHOULD be provided so they can be deobfuscated.</p>
    */
    val exceptionType: String? = null,
    /**
    * <p>Human readable operating system name.</p>
    */
    val osName: String? = null,
    /**
    * <p>The version string of the operating system as defined in <a href="/docs/resource/README.md#version-attributes">Version Attributes</a>.</p>
    */
    val osVersion: String? = null,
    /**
    * <p>The version string of the service component. The format is not defined by these conventions.</p>
    */
    val serviceVersion: String? = null,
    /**
    * <p>A unique id to identify a session.</p>
    */
    val sessionId: String? = null,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "app.crash",
        ) {
            appBuildId?.let { setStringAttribute("app.build_id", it) }
            appCrashId?.let { setStringAttribute("app.crash.id", it) }
            exceptionMessage?.let { setStringAttribute("exception.message", it) }
            exceptionStacktrace?.let { setStringAttribute("exception.stacktrace", it) }
            exceptionType?.let { setStringAttribute("exception.type", it) }
            osName?.let { setStringAttribute("os.name", it) }
            osVersion?.let { setStringAttribute("os.version", it) }
            serviceVersion?.let { setStringAttribute("service.version", it) }
            sessionId?.let { setStringAttribute("session.id", it) }
            attributes?.invoke(this)
        }
    }
}