package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'app.jank'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>This event indicates that the application has detected substandard UI rendering performance.</p>
* <p>Notes:</p>
* <p>Jank happens when the UI is rendered slowly enough for the user to experience some disruption or sluggishness.</p>
*/
@ExperimentalApi
@IncubatingApi
class AppJankEvent(
    /**
    * <p>A number of frame renders that experienced jank.</p>
    * <p>Notes:</p>
    * <p>Depending on platform limitations, the value provided MAY be approximation.</p>
    */
    val appJankFrameCount: Long? = null,
    /**
    * <p>The time period, in seconds, for which this jank is being reported.</p>
    */
    val appJankPeriod: Double? = null,
    /**
    * <p>The minimum rendering threshold for this jank, in seconds.</p>
    */
    val appJankThreshold: Double? = null,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "app.jank",
        ) {
            appJankFrameCount?.let { setLongAttribute("app.jank.frame_count", it) }
            appJankPeriod?.let { setDoubleAttribute("app.jank.period", it) }
            appJankThreshold?.let { setDoubleAttribute("app.jank.threshold", it) }
            attributes?.invoke(this)
        }
    }
}