package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'app.nav_complete'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>Fired when an app navigation event has completed.</p>
* <p>Notes:</p>
* <p>none</p>
*/
@ExperimentalApi
@IncubatingApi
class AppNavCompleteEvent(
    /**
    * <p>A human-readable string that uniquely identifies the destination of app navigation. This value should not contain high-cardinality dimensions like user ID, which should be replaced with a generic token if programmatically determined.</p>
    */
    val appNavDestination: String? = null,
    /**
    * <p>A unique id to identify a session.</p>
    */
    val sessionId: String? = null,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "app.nav_complete",
        ) {
            appNavDestination?.let { setStringAttribute("app.nav.destination", it) }
            sessionId?.let { setStringAttribute("session.id", it) }
            attributes?.invoke(this)
        }
    }
}