package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'app.screen.click'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>This event represents an instantaneous click on the screen of an application.</p>
* <p>Notes:</p>
* <p>The <c>app.screen.click</c> event can be used to indicate that a user has clicked or tapped on the screen portion of an application. Clicks outside of an application's active area SHOULD NOT generate this event. This event does not differentiate between touch/mouse down and touch/mouse up. Implementations SHOULD give preference to generating this event at the time the click is complete, typically on touch release or mouse up. The location of the click event MUST be provided in absolute screen pixels.</p>
*/
@ExperimentalApi
@OptIn(IncubatingApi::class)
class AppScreenClickEvent(
    /**
    * <p>The x (horizontal) coordinate of a screen coordinate, in screen pixels.</p>
    */
    val appScreenCoordinateX: Long,
    /**
    * <p>The y (vertical) component of a screen coordinate, in screen pixels.</p>
    */
    val appScreenCoordinateY: Long,
    /**
    * <p>An identifier that uniquely differentiates this screen from other screens in the same application.</p>
    * <p>Notes:</p>
    * <p>A screen represents only the part of the device display drawn by the app. It typically contains multiple widgets or UI components and is larger in scope than individual widgets. Multiple screens can coexist on the same display simultaneously (e.g., split view on tablets).</p>
    */
    val appScreenId: String? = null,
    /**
    * <p>The name of an application screen.</p>
    * <p>Notes:</p>
    * <p>A screen represents only the part of the device display drawn by the app. It typically contains multiple widgets or UI components and is larger in scope than individual widgets. Multiple screens can coexist on the same display simultaneously (e.g., split view on tablets).</p>
    */
    val appScreenName: String? = null,
) : OpenTelemetryEvent {

    override fun emit(logger: Logger) {
        logger.emit(
            eventName = "app.screen.click",
        ) {
            setLongAttribute("app.screen.coordinate.x", appScreenCoordinateX)
            setLongAttribute("app.screen.coordinate.y", appScreenCoordinateY)
            appScreenId?.let { setStringAttribute("app.screen.id", it) }
            appScreenName?.let { setStringAttribute("app.screen.name", it) }
        }
    }
}