package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'az.resource.log'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>Deprecated. Use <c>azure.resource.log</c> instead.</p>
* <p>Notes:</p>
* <p>none</p>
*/
@ExperimentalApi
@IncubatingApi
@Deprecated("Replaced by `azure.resource.log`.")
class AzResourceLogEvent(
    /**
    * <p>Deprecated, use <c>azure.service.request.id</c> instead.</p>
    */
    val azServiceRequestId: String? = null,
    /**
    * <p>The <a href="https://learn.microsoft.com/rest/api/resources/resources/get-by-id">Fully Qualified Azure Resource ID</a> the log is emitted for.</p>
    */
    val cloudResourceId: String? = null,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "az.resource.log",
        ) {
            azServiceRequestId?.let { setStringAttribute("az.service_request_id", it) }
            cloudResourceId?.let { setStringAttribute("cloud.resource_id", it) }
            attributes?.invoke(this)
        }
    }
}