package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'browser.web_vital'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>This event describes the website performance metrics introduced by Google, See <a href="https://web.dev/vitals">web vitals</a>.</p>
* <p>Notes:</p>
* <p>none</p>
*/
@ExperimentalApi
@IncubatingApi
class BrowserWebVitalEvent(
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "browser.web_vital",
        ) {
            attributes?.invoke(this)
        }
    }
}