package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'device.app.lifecycle'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>This event represents an occurrence of a lifecycle transition on Android or iOS platform.</p>
* <p>Notes:</p>
* <p>The event body fields MUST be used to describe the state of the application at the time of the event.
* This event is meant to be used in conjunction with <c>os.name</c> <a href="/docs/resource/os.md">resource semantic convention</a> to identify the mobile operating system (e.g. Android, iOS).
* The <c>android.app.state</c> and <c>ios.app.state</c> fields are mutually exclusive and MUST NOT be used together, each field MUST be used with its corresponding <c>os.name</c> value.</p>
*/
@ExperimentalApi
@IncubatingApi
class DeviceAppLifecycleEvent(
    /**
    * <p>This attribute represents the state of the application.</p>
    * <p>Notes:</p>
    * <p>The Android lifecycle states are defined in <a href="https://developer.android.com/guide/components/activities/activity-lifecycle#lifecycle-callbacks">Activity lifecycle callbacks</a>, and from which the <c>OS identifiers</c> are derived.</p>
    */
    val androidAppState: String? = null,
    /**
    * <p>This attribute represents the state of the application.</p>
    * <p>Notes:</p>
    * <p>The iOS lifecycle states are defined in the <a href="https://developer.apple.com/documentation/uikit/uiapplicationdelegate">UIApplicationDelegate documentation</a>, and from which the <c>OS terminology</c> column values are derived.</p>
    */
    val iosAppState: String? = null,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "device.app.lifecycle",
        ) {
            androidAppState?.let { setStringAttribute("android.app.state", it) }
            iosAppState?.let { setStringAttribute("ios.app.state", it) }
            attributes?.invoke(this)
        }
    }
}