package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'feature_flag.evaluation'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>Defines feature flag evaluation as an event.</p>
* <p>Notes:</p>
* <p>A <c>feature_flag.evaluation</c> event SHOULD be emitted whenever a feature flag value is evaluated, which may happen many times over the course of an application lifecycle. For example, a website A/B testing different animations may evaluate a flag each time a button is clicked. A <c>feature_flag.evaluation</c> event is emitted on each evaluation even if the result is the same.</p>
*/
@ExperimentalApi
@IncubatingApi
class FeatureFlagEvaluationEvent(
    /**
    * <p>Describes a class of error the operation ended with.</p>
    * <p>Notes:</p>
    * <p>If one of these values applies, then it MUST be used; otherwise, a custom value MAY be used.</p>
    * <p>| Value | Description | Stability |
    * | --- | --- | --- |
    * | <c>flag_not_found</c> | The flag could not be found. |  |
    * | <c>invalid_context</c> | The evaluation context does not meet provider requirements. |  |
    * | <c>parse_error</c> | An error was encountered parsing data, such as a flag configuration. |  |
    * | <c>provider_fatal</c> | The provider has entered an irrecoverable error state. |  |
    * | <c>provider_not_ready</c> | The value was resolved before the provider was initialized. |  |
    * | <c>targeting_key_missing</c> | The provider requires a targeting key and one was not provided in the evaluation context. |  |
    * | <c>type_mismatch</c> | The type of the flag value does not match the expected type. |  |
    * | <c>general</c> | The error was for a reason not enumerated above. |  |</p>
    */
    val errorType: String? = null,
    /**
    * <p>The unique identifier for the flag evaluation context. For example, the targeting key.</p>
    */
    val featureFlagContextId: String? = null,
    /**
    * <p>A message providing more detail about an error that occurred during feature flag evaluation in human-readable form.</p>
    * <p>Notes:</p>
    * <p>Should not simply duplicate the value of <c>error.type</c>, but should provide more context. For example, if <c>error.type</c> is <c>invalid_context</c> the <c>feature_flag.error.message</c> may enumerate which context keys are missing or invalid.</p>
    */
    val featureFlagErrorMessage: String? = null,
    /**
    * <p>The lookup key of the feature flag.</p>
    */
    val featureFlagKey: String,
    /**
    * <p>Identifies the feature flag provider.</p>
    */
    val featureFlagProviderName: String? = null,
    /**
    * <p>The reason code which shows how a feature flag value was determined.</p>
    */
    val featureFlagResultReason: String? = null,
    /**
    * <p>The evaluated value of the feature flag.</p>
    * <p>Notes:</p>
    * <p>With some feature flag providers, feature flag results can be quite large or contain private or sensitive details.
    * Because of this, <c>feature_flag.result.variant</c> is often the preferred attribute if it is available.</p>
    * <p>It may be desirable to redact or otherwise limit the size and scope of <c>feature_flag.result.value</c> if possible.
    * Because the evaluated flag value is unstructured and may be any type, it is left to the instrumentation author to determine how best to achieve this.</p>
    */
    val featureFlagResultValue: AnyValue? = null,
    /**
    * <p>A semantic identifier for an evaluated flag value.</p>
    * <p>Notes:</p>
    * <p>A semantic identifier, commonly referred to as a variant, provides a means
    * for referring to a value without including the value itself. This can
    * provide additional context for understanding the meaning behind a value.
    * For example, the variant <c>red</c> maybe be used for the value <c>#c05543</c>.</p>
    */
    val featureFlagResultVariant: String? = null,
    /**
    * <p>The identifier of the <a href="https://openfeature.dev/specification/glossary/#flag-set">flag set</a> to which the feature flag belongs.</p>
    */
    val featureFlagSetId: String? = null,
    /**
    * <p>The version of the ruleset used during the evaluation. This may be any stable value which uniquely identifies the ruleset.</p>
    */
    val featureFlagVersion: String? = null,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "feature_flag.evaluation",
        ) {
            errorType?.let { setStringAttribute("error.type", it) }
            featureFlagContextId?.let { setStringAttribute("feature_flag.context.id", it) }
            featureFlagErrorMessage?.let { setStringAttribute("feature_flag.error.message", it) }
            setStringAttribute("feature_flag.key", featureFlagKey)
            featureFlagProviderName?.let { setStringAttribute("feature_flag.provider.name", it) }
            featureFlagResultReason?.let { setStringAttribute("feature_flag.result.reason", it) }
            featureFlagResultValue?.let { setAnyValueAttribute("feature_flag.result.value", it) }
            featureFlagResultVariant?.let { setStringAttribute("feature_flag.result.variant", it) }
            featureFlagSetId?.let { setStringAttribute("feature_flag.set.id", it) }
            featureFlagVersion?.let { setStringAttribute("feature_flag.version", it) }
            attributes?.invoke(this)
        }
    }
}