package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'gen_ai.evaluation.result'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>This event captures the result of evaluating GenAI output for quality, accuracy, or other characteristics. This event SHOULD be parented to GenAI operation span being evaluated when possible or set <c>gen_ai.response.id</c> when span id is not available.</p>
* <p>Notes:</p>
* <p>none</p>
*/
@ExperimentalApi
@IncubatingApi
@Deprecated("Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).")
class GenAiEvaluationResultEvent(
    /**
    * <p>Describes a class of error the operation ended with.</p>
    * <p>Notes:</p>
    * <p>The <c>error.type</c> SHOULD match the error code returned by the Generative AI Evaluation provider or the client library,
    * the canonical name of exception that occurred, or another low-cardinality error identifier.
    * Instrumentations SHOULD document the list of errors they report.</p>
    */
    val errorType: String? = null,
    /**
    * <p>A free-form explanation for the assigned score provided by the evaluator.</p>
    */
    val genAiEvaluationExplanation: String? = null,
    /**
    * <p>The name of the evaluation metric used for the GenAI response.</p>
    */
    val genAiEvaluationName: String,
    /**
    * <p>Human readable label for evaluation.</p>
    * <p>Notes:</p>
    * <p>This attribute provides a human-readable interpretation of the evaluation score produced by an evaluator. For example, a score value of 1 could mean "relevant" in one evaluation system and "not relevant" in another, depending on the scoring range and evaluator. The label SHOULD have low cardinality. Possible values depend on the evaluation metric and evaluator used; implementations SHOULD document the possible values.</p>
    */
    val genAiEvaluationScoreLabel: String? = null,
    /**
    * <p>The evaluation score returned by the evaluator.</p>
    */
    val genAiEvaluationScoreValue: Double? = null,
    /**
    * <p>The unique identifier for the completion.</p>
    * <p>Notes:</p>
    * <p>The unique identifier assigned to the specific
    * completion being evaluated. This attribute helps correlate the evaluation
    * event with the corresponding operation when span id is not available.</p>
    */
    val genAiResponseId: String? = null,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "gen_ai.evaluation.result",
        ) {
            errorType?.let { setStringAttribute("error.type", it) }
            genAiEvaluationExplanation?.let { setStringAttribute("gen_ai.evaluation.explanation", it) }
            setStringAttribute("gen_ai.evaluation.name", genAiEvaluationName)
            genAiEvaluationScoreLabel?.let { setStringAttribute("gen_ai.evaluation.score.label", it) }
            genAiEvaluationScoreValue?.let { setDoubleAttribute("gen_ai.evaluation.score.value", it) }
            genAiResponseId?.let { setStringAttribute("gen_ai.response.id", it) }
            attributes?.invoke(this)
        }
    }
}