package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'gen_ai.client.inference.operation.details'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>Describes the details of a GenAI completion request including chat history and parameters.</p>
* <p>Notes:</p>
* <p>This event is opt-in and could be used to store input and output details independently from traces.</p>
*/
@ExperimentalApi
@IncubatingApi
@Deprecated("Moved to the [OpenTelemetry GenAI semantic conventions repository](https://github.com/open-telemetry/semantic-conventions-genai).")
class GenAiClientInferenceOperationDetailsEvent(
    /**
    * <p>Describes a class of error the operation ended with.</p>
    * <p>Notes:</p>
    * <p>The <c>error.type</c> SHOULD match the error code returned by the Generative AI provider or the client library,
    * the canonical name of exception that occurred, or another low-cardinality error identifier.
    * Instrumentations SHOULD document the list of errors they report.</p>
    */
    val errorType: String? = null,
    /**
    * <p>The unique identifier for a conversation (session, thread), used to store and correlate messages within this conversation.</p>
    * <p>Notes:</p>
    * <p>Instrumentations SHOULD populate conversation id when they have it readily available
    * for a given operation, for example:</p>
    * <ul>
    *   <li>when client framework being instrumented manages conversation history
    * (see <a href="https://docs.llamaindex.ai/en/stable/module_guides/storing/chat_stores/">LlamaIndex chat store</a>)</li>
    *   <li>when instrumenting GenAI client libraries that maintain conversation on the backend side
    * (see <a href="https://docs.aws.amazon.com/bedrock/latest/userguide/agents-session-state.html">AWS Bedrock agent sessions</a>,
    * <a href="https://platform.openai.com/docs/api-reference/threads">OpenAI Assistant threads</a>)</li>
    * </ul>
    * <p>Application developers that manage conversation history MAY add conversation id to GenAI and other
    * spans or logs using custom span or log record processors or hooks provided by instrumentation
    * libraries.</p>
    */
    val genAiConversationId: String? = null,
    /**
    * <p>The chat history provided to the model as an input.</p>
    * <p>Notes:</p>
    * <p>Instrumentations MUST follow <a href="https://github.com/open-telemetry/semantic-conventions/blob/v1.41.0/docs/gen-ai/gen-ai-input-messages.json">Input messages JSON schema</a>.
    * When the attribute is recorded on events, it MUST be recorded in structured
    * form. When recorded on spans, it MAY be recorded as a JSON string if structured
    * format is not supported and SHOULD be recorded in structured form otherwise.</p>
    * <p>Messages MUST be provided in the order they were sent to the model.
    * Instrumentations MAY provide a way for users to filter or truncate
    * input messages.</p>
    * <blockquote>
    * <p>[!Warning]
    * This attribute is likely to contain sensitive information including user/PII data.</p></blockquote>
    * <p>See <a href="https://github.com/open-telemetry/semantic-conventions/blob/v1.41.0/docs/gen-ai/gen-ai-spans.md#recording-content-on-attributes">Recording content on attributes</a>
    * section for more details.</p>
    */
    val genAiInputMessages: AnyValue? = null,
    /**
    * <p>The name of the operation being performed.</p>
    * <p>Notes:</p>
    * <p>If one of the predefined values applies, but specific system uses a different name it's RECOMMENDED to document it in the semantic conventions for specific GenAI system and use system-specific name in the instrumentation. If a different name is not documented, instrumentation libraries SHOULD use applicable predefined value.</p>
    */
    val genAiOperationName: String,
    /**
    * <p>Messages returned by the model where each message represents a specific model response (choice, candidate).</p>
    * <p>Notes:</p>
    * <p>Instrumentations MUST follow <a href="https://github.com/open-telemetry/semantic-conventions/blob/v1.41.0/docs/gen-ai/gen-ai-output-messages.json">Output messages JSON schema</a></p>
    * <p>Each message represents a single output choice/candidate generated by
    * the model. Each message corresponds to exactly one generation
    * (choice/candidate) and vice versa - one choice cannot be split across
    * multiple messages or one message cannot contain parts from multiple choices.</p>
    * <p>When the attribute is recorded on events, it MUST be recorded in structured
    * form. When recorded on spans, it MAY be recorded as a JSON string if structured
    * format is not supported and SHOULD be recorded in structured form otherwise.</p>
    * <p>Instrumentations MAY provide a way for users to filter or truncate
    * output messages.</p>
    * <blockquote>
    * <p>[!Warning]
    * This attribute is likely to contain sensitive information including user/PII data.</p></blockquote>
    * <p>See <a href="https://github.com/open-telemetry/semantic-conventions/blob/v1.41.0/docs/gen-ai/gen-ai-spans.md#recording-content-on-attributes">Recording content on attributes</a>
    * section for more details.</p>
    */
    val genAiOutputMessages: AnyValue? = null,
    /**
    * <p>Represents the content type requested by the client.</p>
    * <p>Notes:</p>
    * <p>This attribute SHOULD be used when the client requests output of a specific type. The model may return zero or more outputs of this type.
    * This attribute specifies the output modality and not the actual output format. For example, if an image is requested, the actual output could be a URL pointing to an image file.
    * Additional output format details may be recorded in the future in the <c>gen_ai.output.{type}.*</c> attributes.</p>
    */
    val genAiOutputType: String? = null,
    /**
    * <p>The target number of candidate completions to return.</p>
    */
    val genAiRequestChoiceCount: Long? = null,
    /**
    * <p>The frequency penalty setting for the GenAI request.</p>
    */
    val genAiRequestFrequencyPenalty: Double? = null,
    /**
    * <p>The maximum number of tokens the model generates for a request.</p>
    */
    val genAiRequestMaxTokens: Long? = null,
    /**
    * <p>The name of the GenAI model a request is being made to.</p>
    * <p>Notes:</p>
    * <p>The name of the GenAI model a request is being made to. If the model is supplied by a vendor, then the value must be the exact name of the model requested. If the model is a fine-tuned custom model, the value should have a more specific name than the base model that's been fine-tuned.</p>
    */
    val genAiRequestModel: String? = null,
    /**
    * <p>The presence penalty setting for the GenAI request.</p>
    */
    val genAiRequestPresencePenalty: Double? = null,
    /**
    * <p>Requests with same seed value more likely to return same result.</p>
    */
    val genAiRequestSeed: Long? = null,
    /**
    * <p>List of sequences that the model will use to stop generating further tokens.</p>
    */
    val genAiRequestStopSequences: List<String>? = null,
    /**
    * <p>Indicates whether the GenAI request was made in streaming mode.</p>
    */
    val genAiRequestStream: Boolean? = null,
    /**
    * <p>The temperature setting for the GenAI request.</p>
    */
    val genAiRequestTemperature: Double? = null,
    /**
    * <p>The top_p sampling setting for the GenAI request.</p>
    */
    val genAiRequestTopP: Double? = null,
    /**
    * <p>Array of reasons the model stopped generating tokens, corresponding to each generation received.</p>
    */
    val genAiResponseFinishReasons: List<String>? = null,
    /**
    * <p>The unique identifier for the completion.</p>
    */
    val genAiResponseId: String? = null,
    /**
    * <p>The name of the model that generated the response.</p>
    * <p>Notes:</p>
    * <p>If available. The name of the GenAI model that provided the response. If the model is supplied by a vendor, then the value must be the exact name of the model actually used. If the model is a fine-tuned custom model, the value should have a more specific name than the base model that's been fine-tuned.</p>
    */
    val genAiResponseModel: String? = null,
    /**
    * <p>Time to first chunk in a streaming response, measured from request issuance, in seconds. The value is measured from when the client issues the generation request to when the first chunk is received in the response stream.</p>
    */
    val genAiResponseTimeToFirstChunk: Double? = null,
    /**
    * <p>The system message or instructions provided to the GenAI model separately from the chat history.</p>
    * <p>Notes:</p>
    * <p>This attribute SHOULD be used when the corresponding provider or API
    * allows to provide system instructions or messages separately from the
    * chat history.</p>
    * <p>Instructions that are part of the chat history SHOULD be recorded in
    * <c>gen_ai.input.messages</c> attribute instead.</p>
    * <p>Instrumentations MUST follow <a href="https://github.com/open-telemetry/semantic-conventions/blob/v1.41.0/docs/gen-ai/gen-ai-system-instructions.json">System instructions JSON schema</a>.</p>
    * <p>When recorded on spans, it MAY be recorded as a JSON string if structured
    * format is not supported and SHOULD be recorded in structured form otherwise.</p>
    * <p>Instrumentations MAY provide a way for users to filter or truncate
    * system instructions.</p>
    * <blockquote>
    * <p>[!Warning]
    * This attribute may contain sensitive information.</p></blockquote>
    * <p>See <a href="https://github.com/open-telemetry/semantic-conventions/blob/v1.41.0/docs/gen-ai/gen-ai-spans.md#recording-content-on-attributes">Recording content on attributes</a>
    * section for more details.</p>
    */
    val genAiSystemInstructions: AnyValue? = null,
    /**
    * <p>The list of tool definitions available to the GenAI agent or model.</p>
    * <p>Notes:</p>
    * <p>Instrumentations MUST follow <a href="https://github.com/open-telemetry/semantic-conventions/blob/v1.41.0/docs/gen-ai/gen-ai-tool-definitions.json">Tool Definitions JSON Schema</a>.</p>
    * <p>When the attribute is recorded on events, it MUST be recorded in structured
    * form. When recorded on spans, it MAY be recorded as a JSON string if structured
    * format is not supported and SHOULD be recorded in structured form otherwise.</p>
    * <p>Since this attribute could be large, it's NOT RECOMMENDED to populate
    * non-required properties by default. Instrumentations MAY provide a way
    * to enable populating optional properties.</p>
    */
    val genAiToolDefinitions: AnyValue? = null,
    /**
    * <p>The number of input tokens written to a provider-managed cache.</p>
    * <p>Notes:</p>
    * <p>The value SHOULD be included in <c>gen_ai.usage.input_tokens</c>.</p>
    */
    val genAiUsageCacheCreationInputTokens: Long? = null,
    /**
    * <p>The number of input tokens served from a provider-managed cache.</p>
    * <p>Notes:</p>
    * <p>The value SHOULD be included in <c>gen_ai.usage.input_tokens</c>.</p>
    */
    val genAiUsageCacheReadInputTokens: Long? = null,
    /**
    * <p>The number of tokens used in the GenAI input (prompt).</p>
    * <p>Notes:</p>
    * <p>This value SHOULD include all types of input tokens, including cached tokens.
    * Instrumentations SHOULD make a best effort to populate this value, using a total
    * provided by the provider when available or, depending on the provider API,
    * by summing different token types parsed from the provider output.</p>
    */
    val genAiUsageInputTokens: Long? = null,
    /**
    * <p>The number of tokens used in the GenAI response (completion).</p>
    */
    val genAiUsageOutputTokens: Long? = null,
    /**
    * <p>The number of output tokens used for reasoning (e.g. chain-of-thought, extended thinking).</p>
    * <p>Notes:</p>
    * <p>The value SHOULD be included in <c>gen_ai.usage.output_tokens</c>.</p>
    */
    val genAiUsageReasoningOutputTokens: Long? = null,
    /**
    * <p>GenAI server address.</p>
    * <p>Notes:</p>
    * <p>When observed from the client side, and when communicating through an intermediary, <c>server.address</c> SHOULD represent the server address behind any intermediaries, for example proxies, if it's available.</p>
    */
    val serverAddress: String? = null,
    /**
    * <p>GenAI server port.</p>
    * <p>Notes:</p>
    * <p>When observed from the client side, and when communicating through an intermediary, <c>server.port</c> SHOULD represent the server port behind any intermediaries, for example proxies, if it's available.</p>
    */
    val serverPort: Long? = null,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "gen_ai.client.inference.operation.details",
        ) {
            errorType?.let { setStringAttribute("error.type", it) }
            genAiConversationId?.let { setStringAttribute("gen_ai.conversation.id", it) }
            genAiInputMessages?.let { setAnyValueAttribute("gen_ai.input.messages", it) }
            setStringAttribute("gen_ai.operation.name", genAiOperationName)
            genAiOutputMessages?.let { setAnyValueAttribute("gen_ai.output.messages", it) }
            genAiOutputType?.let { setStringAttribute("gen_ai.output.type", it) }
            genAiRequestChoiceCount?.let { setLongAttribute("gen_ai.request.choice.count", it) }
            genAiRequestFrequencyPenalty?.let { setDoubleAttribute("gen_ai.request.frequency_penalty", it) }
            genAiRequestMaxTokens?.let { setLongAttribute("gen_ai.request.max_tokens", it) }
            genAiRequestModel?.let { setStringAttribute("gen_ai.request.model", it) }
            genAiRequestPresencePenalty?.let { setDoubleAttribute("gen_ai.request.presence_penalty", it) }
            genAiRequestSeed?.let { setLongAttribute("gen_ai.request.seed", it) }
            genAiRequestStopSequences?.let { setStringListAttribute("gen_ai.request.stop_sequences", it) }
            genAiRequestStream?.let { setBooleanAttribute("gen_ai.request.stream", it) }
            genAiRequestTemperature?.let { setDoubleAttribute("gen_ai.request.temperature", it) }
            genAiRequestTopP?.let { setDoubleAttribute("gen_ai.request.top_p", it) }
            genAiResponseFinishReasons?.let { setStringListAttribute("gen_ai.response.finish_reasons", it) }
            genAiResponseId?.let { setStringAttribute("gen_ai.response.id", it) }
            genAiResponseModel?.let { setStringAttribute("gen_ai.response.model", it) }
            genAiResponseTimeToFirstChunk?.let { setDoubleAttribute("gen_ai.response.time_to_first_chunk", it) }
            genAiSystemInstructions?.let { setAnyValueAttribute("gen_ai.system_instructions", it) }
            genAiToolDefinitions?.let { setAnyValueAttribute("gen_ai.tool.definitions", it) }
            genAiUsageCacheCreationInputTokens?.let { setLongAttribute("gen_ai.usage.cache_creation.input_tokens", it) }
            genAiUsageCacheReadInputTokens?.let { setLongAttribute("gen_ai.usage.cache_read.input_tokens", it) }
            genAiUsageInputTokens?.let { setLongAttribute("gen_ai.usage.input_tokens", it) }
            genAiUsageOutputTokens?.let { setLongAttribute("gen_ai.usage.output_tokens", it) }
            genAiUsageReasoningOutputTokens?.let { setLongAttribute("gen_ai.usage.reasoning.output_tokens", it) }
            serverAddress?.let { setStringAttribute("server.address", it) }
            serverPort?.let { setLongAttribute("server.port", it) }
            attributes?.invoke(this)
        }
    }
}