package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'gen_ai.assistant.message'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>This event describes the assistant message passed to GenAI system.</p>
* <p>Notes:</p>
* <p>none</p>
*/
@ExperimentalApi
@IncubatingApi
@Deprecated("Chat history is reported on `gen_ai.input.messages` attribute on spans or `gen_ai.client.inference.operation.details` event.")
class GenAiAssistantMessageEvent(
    /**
    * <p>Deprecated, use <c>gen_ai.provider.name</c> instead.</p>
    */
    val genAiSystem: String? = null,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "gen_ai.assistant.message",
        ) {
            genAiSystem?.let { setStringAttribute("gen_ai.system", it) }
            attributes?.invoke(this)
        }
    }
}