package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'messaging.process.exception'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>This event represents an exception that occurred during messaging process operations.</p>
* <p>Notes:</p>
* <p>This event SHOULD be recorded when an exception occurs during messaging process operations.
* Instrumentations SHOULD set the severity to ERROR (severity number 17) when recording this event.
* Instrumentations MAY provide a configuration option to populate exception events with the attributes captured on the corresponding messaging process span.</p>
*/
@ExperimentalApi
@IncubatingApi
class MessagingProcessExceptionEvent(
    /**
    * <p>The exception message.</p>
    * <p>Notes:</p>
    * <blockquote>
    * <p>[!WARNING]</p>
    * <p>This attribute may contain sensitive information.</p></blockquote>
    */
    val exceptionMessage: String? = null,
    /**
    * <p>A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG.</p>
    */
    val exceptionStacktrace: String? = null,
    /**
    * <p>The type of the exception (its fully-qualified class name, if applicable). The dynamic type of the exception should be preferred over the static type in languages that support it.</p>
    * <p>Notes:</p>
    * <p>If the recorded exception type is a wrapper that is not meaningful for
    * failure classification, instrumentation MAY use the type of the inner
    * exception instead. For example, in Go, errors created with <c>fmt.Errorf</c>
    * using <c>%w</c> MAY be unwrapped when the wrapper type does not help
    * classify the failure.</p>
    */
    val exceptionType: String? = null,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "messaging.process.exception",
        ) {
            exceptionMessage?.let { setStringAttribute("exception.message", it) }
            exceptionStacktrace?.let { setStringAttribute("exception.stacktrace", it) }
            exceptionType?.let { setStringAttribute("exception.type", it) }
            attributes?.invoke(this)
        }
    }
}