package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'rpc.message'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>Describes a message sent or received within the context of an RPC call.</p>
* <p>Notes:</p>
* <p>In the lifetime of an RPC stream, an event for each message sent/received on client and server spans SHOULD be created. In case of unary calls message events SHOULD NOT be recorded.</p>
*/
@ExperimentalApi
@IncubatingApi
@Deprecated("Deprecated, no replacement at this time.")
class RpcMessageEvent(
    /**
    * <p>Compressed size of the message in bytes.</p>
    */
    val rpcMessageCompressedSize: Long? = null,
    /**
    * <p>MUST be calculated as two different counters starting from <c>1</c> one for sent messages and one for received message.</p>
    * <p>Notes:</p>
    * <p>This way we guarantee that the values will be consistent between different implementations.</p>
    */
    val rpcMessageId: Long? = null,
    /**
    * <p>Whether this is a received or sent message.</p>
    */
    val rpcMessageType: String? = null,
    /**
    * <p>Uncompressed size of the message in bytes.</p>
    */
    val rpcMessageUncompressedSize: Long? = null,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "rpc.message",
        ) {
            rpcMessageCompressedSize?.let { setLongAttribute("rpc.message.compressed_size", it) }
            rpcMessageId?.let { setLongAttribute("rpc.message.id", it) }
            rpcMessageType?.let { setStringAttribute("rpc.message.type", it) }
            rpcMessageUncompressedSize?.let { setLongAttribute("rpc.message.uncompressed_size", it) }
            attributes?.invoke(this)
        }
    }
}