package io.opentelemetry.kotlin.semconv.events

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.attributes.AnyValue
import io.opentelemetry.kotlin.attributes.AttributesMutator
import io.opentelemetry.kotlin.logging.Logger
import io.opentelemetry.kotlin.semconv.IncubatingApi

// Autogenerated OpenTelemetry semantic convention event for 'session.end'.
//
// DO NOT EDIT - AUTOGENERATED FILE
/**
* <p>Indicates that a session has ended.</p>
* <p>Notes:</p>
* <p>For instrumentation that tracks user behavior during user sessions, a <c>session.end</c> event SHOULD be emitted every time a session ends. When a session ends and continues as a new session, this event SHOULD be emitted prior to the <c>session.start</c> event.</p>
*/
@ExperimentalApi
@IncubatingApi
class SessionEndEvent(
    /**
    * <p>The ID of the session being ended.</p>
    */
    val sessionId: String,
) : OpenTelemetryEvent {

    override fun emit(
        logger: Logger,
        attributes: (AttributesMutator.() -> Unit)?,
    ) {
        logger.emit(
            eventName = "session.end",
        ) {
            setStringAttribute("session.id", sessionId)
            attributes?.invoke(this)
        }
    }
}