package io.opentelemetry.kotlin.factory

import io.opentelemetry.kotlin.ExperimentalApi

@ExperimentalApi
public interface IdGenerator {

    /**
     * Generates a new ID for a span.
     */
    public fun generateSpanIdBytes(): ByteArray

    /**
     * Generates a new ID for a trace.
     */
    public fun generateTraceIdBytes(): ByteArray

    /**
     * An invalid trace ID.
     */
    public val invalidTraceId: ByteArray

    /**
     * An invalid span ID.
     */
    public val invalidSpanId: ByteArray

    /**
     * Declares whether every trace ID generated by this [IdGenerator] has its lower 56 bits
     * uniformly distributed over the [0, 2^56-1] interval, meeting
     * [W3C Trace Context Level 2 randomness requirements](https://www.w3.org/TR/trace-context-2/#random-trace-id-flag).
     */
    public val generatesRandomTraceIds: Boolean
        get() = false
}

/**
 * Encodes Span/Trace ID bytes as a hex string.
 */
@ExperimentalApi
public fun ByteArray.toHexString(): String {
    val result = StringBuilder(size * 2)
    for (b in this) {
        val i = b.toInt() and 0xFF
        result.append(i.toString(16).padStart(2, '0'))
    }
    return result.toString()
}

/**
 * Encodes Span/Trace ID hex string as a ByteArray.
 * A string that is not in the expected format return an empty [ByteArray]
 */
@ExperimentalApi
public fun String.hexToByteArray(): ByteArray =
    runCatching {
        require(length % 2 == 0)
        val out = ByteArray(length / 2)
        for (i in out.indices) {
            val hi = this[i * 2].digitToInt(16)
            val lo = this[i * 2 + 1].digitToInt(16)
            out[i] = ((hi shl 4) or lo).toByte()
        }
        out
    }.getOrDefault(ByteArray(0))
