package io.opentelemetry.kotlin.factory

import io.opentelemetry.kotlin.ExperimentalApi

@ExperimentalApi
public interface IdGenerator {

    /**
     * Generates a new ID for a span.
     */
    public fun generateSpanIdBytes(): ByteArray

    /**
     * Generates a new ID for a trace.
     */
    public fun generateTraceIdBytes(): ByteArray

    /**
     * An invalid trace ID.
     */
    public val invalidTraceId: ByteArray

    /**
     * An invalid span ID.
     */
    public val invalidSpanId: ByteArray

    /**
     * Declares whether every trace ID generated by this [IdGenerator] has its lower 56 bits
     * uniformly distributed over the [0, 2^56-1] interval, meeting
     * [W3C Trace Context Level 2 randomness requirements](https://www.w3.org/TR/trace-context-2/#random-trace-id-flag).
     */
    public val generatesRandomTraceIds: Boolean
        get() = false
}

/** Lowercase hex digits, indexed by nibble value. */
private val HEX_DIGITS = "0123456789abcdef".toCharArray()

/** ASCII code point -> nibble value, or -1 if the character is not a hex digit. */
private val HEX_VALUES = IntArray(128) { -1 }.apply {
    for (i in 0..9) {
        this['0'.code + i] = i
    }
    for (i in 0..5) {
        this['a'.code + i] = 10 + i
        this['A'.code + i] = 10 + i
    }
}

/**
 * Encodes Span/Trace ID bytes as a hex string.
 */
@ExperimentalApi
public fun ByteArray.toHexString(): String {
    val chars = CharArray(size * 2)
    var index = 0
    for (b in this) {
        val i = b.toInt() and 0xFF
        chars[index++] = HEX_DIGITS[i shr 4]
        chars[index++] = HEX_DIGITS[i and 0x0F]
    }
    return chars.concatToString()
}

/**
 * Encodes Span/Trace ID hex string as a ByteArray.
 * A string that is not in the expected format return an empty [ByteArray]
 */
@ExperimentalApi
public fun String.hexToByteArray(): ByteArray {
    if (length % 2 != 0) {
        return ByteArray(0)
    }
    val out = ByteArray(length / 2)
    for (i in out.indices) {
        val hi = nibbleAt(i * 2)
        val lo = nibbleAt(i * 2 + 1)
        if (hi < 0 || lo < 0) {
            return ByteArray(0)
        }
        out[i] = ((hi shl 4) or lo).toByte()
    }
    return out
}

/** Returns the nibble value of the hex digit at [index], or -1 if it isn't one. */
private fun String.nibbleAt(index: Int): Int {
    val code = this[index].code
    if (code >= HEX_VALUES.size) {
        return -1
    }
    return HEX_VALUES[code]
}
