package io.opentelemetry.kotlin.factory

import io.opentelemetry.kotlin.ExperimentalApi
import io.opentelemetry.kotlin.propagation.utils.decodeHexOrEmpty
import io.opentelemetry.kotlin.propagation.utils.encodeHex

@ExperimentalApi
public interface IdGenerator {

    /**
     * Generates a new ID for a span.
     */
    public fun generateSpanIdBytes(): ByteArray

    /**
     * Generates a new ID for a trace.
     */
    public fun generateTraceIdBytes(): ByteArray

    /**
     * An invalid trace ID.
     */
    public val invalidTraceId: ByteArray

    /**
     * An invalid span ID.
     */
    public val invalidSpanId: ByteArray

    /**
     * Declares whether every trace ID generated by this [IdGenerator] has its lower 56 bits
     * uniformly distributed over the [0, 2^56-1] interval, meeting
     * [W3C Trace Context Level 2 randomness requirements](https://www.w3.org/TR/trace-context-2/#random-trace-id-flag).
     */
    public val generatesRandomTraceIds: Boolean
        get() = false
}

/**
 * Encodes Span/Trace ID bytes as a hex string.
 */
@ExperimentalApi
public fun ByteArray.toHexString(): String = encodeHex()

/**
 * Encodes Span/Trace ID hex string as a ByteArray.
 * A string that is not in the expected format return an empty [ByteArray]
 */
@ExperimentalApi
public fun String.hexToByteArray(): ByteArray = decodeHexOrEmpty()
