name: ci-build

on:
  push:
    branches: [ main ]
  pull_request:
  release:
    types: [ released ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  gradle-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Branch
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'adopt'
          java-version: |
            17
            21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Gradle Build
        run: ./gradlew build :benchmark-android:assemble :benchmark-android:compileReleaseAndroidTestKotlin :benchmark-jvm:assemble :examples:example-app-android:assembleRelease koverXmlReport -x :gradle-integration-test:test --stacktrace

      - name: Publish snapshot to Maven local
        run: ./gradlew publishToMavenLocal -PsnapshotPublish=true --stacktrace

      - name: Gradle Integration Test
        run: ./gradlew :gradle-integration-test:test --stacktrace

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: open-telemetry/opentelemetry-kotlin
          fail_ci_if_error: false
          files: build/reports/kover/reportRelease.xml

  required-status-check:
    permissions:
      contents: read
      issues: write
    needs:
      - gradle-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - if: |
          needs.gradle-test.result != 'success'
        run: exit 1
